// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 HYPERI PTY LIMITED
//
// Generated by dfe-codegen. Do not edit.

use dfe_runtime::prelude::*;

/// Transform for the `default` pipeline.
pub struct Default;

impl Transform for Default {
    fn name(&self) -> &str {
        "default"
    }

    fn transform(&self, event: &mut Event) -> Result<TransformResult> {
        event.set("ecs.version", json!("8.11.0"))?;

        // TODO: conditional: ctx.event?.original != null
        {
            event.append("error.message", json!("event.original is set before start of ingest pipeline"))?;
        }

        // TODO: conditional: ctx.event?.original == null
        {
            if event.has("message") {
                event.rename("message", "event.original")?;
            }
        }

            if let Some(s) = event.get_str("event.original").map(String::from) {
            let s = s.as_str();
                let parsed: Value = serde_json::from_str(s)
                    .map_err(|e| TransformError::ParseError {
                        path: "event.original".into(),
                        message: format!("failed to parse JSON: {}", e),
                    })?;
                event.set("json", parsed)?;
            }

            // Painless script
            // Source: boolean drop(Object o) {\n  if (o == null || o == \"\") {\n    return true;\n  } else if (o instanceof Map) {\n    ((Map) o).values().removeIf(v -> drop(v));\n    return (((Map) o).size() == 0);\n  } else if (o instanceof List) {\n    ((List) o).removeIf(v -> drop(v));\n    return (((List) o).length == 0);\n  }\n  return false;\n}\ndrop(ctx);\n
            // TODO: Transpile Painless to Rust (2.2.3)
            painless_exec(event, r#"boolean drop(Object o) {\n  if (o == null || o == \"\") {\n    return true;\n  } else if (o instanceof Map) {\n    ((Map) o).values().removeIf(v -> drop(v));\n    return (((Map) o).size() == 0);\n  } else if (o instanceof List) {\n    ((List) o).removeIf(v -> drop(v));\n    return (((List) o).length == 0);\n  }\n  return false;\n}\ndrop(ctx);\n"#)?;

        // TODO: conditional: ctx?.json?.uuid != null && ctx?.json?.uuid != ""
        {
        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if let Some(val) = event.get("json.uuid") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("_id", converted)?;
            }
            Ok(())
        })();
        }

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if let Some(date_str) = event.get_str("json.published").map(String::from) {
            let date_str = date_str.as_str();
                // Try ISO8601 format
                if let Ok(dt) = chrono::DateTime::parse_from_rfc3339(date_str)
                    .or_else(|_| chrono::DateTime::parse_from_str(date_str, "%Y-%m-%dT%H:%M:%S%.f%:z"))
                    .or_else(|_| chrono::DateTime::parse_from_str(date_str, "%Y-%m-%dT%H:%M:%S%:z"))
                {
                    event.set("@timestamp", dt.to_rfc3339())?;
                }
            }
            Ok(())
        })();

        event.set("event.kind", json!("event"))?;

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.displayMessage") {
                event.rename("json.displayMessage", "okta.display_message")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.eventType") {
                event.rename("json.eventType", "okta.event_type")?;
            }
            Ok(())
        })();

        // TODO: conditional: ["group.user_membership.add","group.user_membership.remove",
// "user.lifecycle.activate","user.lifecycle.create",
// "user.lifecycle.deactivate","user.lifecycle.suspend",
// "user.lifecycle.unsuspend"].contains(ctx?.okta?.event_type)

        {
            event.append("event.category", json!("iam"))?;
        }

        // TODO: conditional: ["policy.lifecycle.activate","policy.lifecycle.create",
// "policy.lifecycle.deactivate","policy.lifecycle.delete",
// "policy.lifecycle.update","policy.rule.activate","policy.rule.add",
// "policy.rule.deactivate","policy.rule.delete",
// "application.lifecycle.create","application.lifecycle.delete",
// "policy.rule.update","application.lifecycle.activate",
// "application.lifecycle.deactivate","application.lifecycle.update"].contains(ctx?.okta?.event_type)

        {
            event.append("event.category", json!("configuration"))?;
        }

        // TODO: conditional: ["user.session.start","user.session.end","user.authentication.sso","policy.evaluate_sign_on"].contains(ctx?.okta?.event_type)
        {
            event.append("event.category", json!("authentication"))?;
        }

        // TODO: conditional: ["user.session.start","user.session.end"].contains(ctx?.okta?.event_type)
        {
            event.append("event.category", json!("session"))?;
        }

        // TODO: conditional: ["system.org.rate_limit.warning","system.org.rate_limit.violation",
// "core.concurrency.org.limit.violation"].contains(ctx?.okta?.event_type)

        {
            event.append("event.type", json!("info"))?;
        }

        // TODO: conditional: ["security.request.blocked"].contains(ctx?.okta?.event_type)
        {
            event.append("event.type", json!("network"))?;
        }

        // TODO: conditional: ["system.org.rate_limit.warning","system.org.rate_limit.violation",
// "core.concurrency.org.limit.violation","security.request.blocked"].contains(ctx?.okta?.event_type)

        {
            event.append("event.type", json!("network"))?;
        }

        // TODO: conditional: ["user.session.start"].contains(ctx?.okta?.event_type)
        {
            event.append("event.type", json!("start"))?;
        }

        // TODO: conditional: ["user.session.end"].contains(ctx?.okta?.event_type)
        {
            event.append("event.type", json!("end"))?;
        }

        // TODO: conditional: ["group.user_membership.add","group.user_membership.remove"].contains(ctx?.okta?.event_type)
        {
            event.append("event.type", json!("group"))?;
        }

        // TODO: conditional: ["user.lifecycle.activate","user.lifecycle.create",
// "user.lifecycle.deactivate","user.lifecycle.suspend",
// "user.lifecycle.unsuspend","user.authentication.sso",
// "user.session.start","user.session.end","application.user_membership.add",
// "application.user_membership.remove","application.user_membership.change_username"].contains(ctx?.okta?.event_type)

        {
            event.append("event.type", json!("info"))?;
        }

        // TODO: conditional: ["user.lifecycle.activate","user.lifecycle.deactivate",
// "user.lifecycle.suspend","user.lifecycle.unsuspend",
// "group.user_membership.add","group.user_membership.remove",
// "policy.lifecycle.activate","policy.lifecycle.deactivate",
// "policy.lifecycle.update","policy.rule.activate","policy.rule.add",
// "policy.rule.deactivate","policy.rule.update","application.user_membership.add",
// "application.user_membership.remove","application.user_membership.change_username"].contains(ctx?.okta?.event_type)

        {
            event.append("event.type", json!("change"))?;
        }

        // TODO: conditional: ["user.lifecycle.create","policy.lifecycle.create","application.lifecycle.create"].contains(ctx?.okta?.event_type)
        {
            event.append("event.type", json!("creation"))?;
        }

        // TODO: conditional: ["policy.lifecycle.delete","application.lifecycle.delete"].contains(ctx?.okta?.event_type)
        {
            event.append("event.type", json!("deletion"))?;
        }

        // TODO: conditional: ["policy.evaluate_sign_on"].contains(ctx?.okta?.event_type)
        {
            event.append("event.type", json!("info"))?;
        }

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.uuid") {
                event.rename("json.uuid", "okta.uuid")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.actor.alternateId") {
                event.rename("json.actor.alternateId", "okta.actor.alternate_id")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
        if event.has("okta.actor.alternate_id") {
            if let Some(input) = event.get_str("okta.actor.alternate_id").map(String::from) {
            let input = input.as_str();
                // Grok pattern: %{USER:user.name}
                // TODO: Replace with dfe-parse Layer 1/2/3 calls after grok analyser (2.1.2)
                let grok_re = regex::Regex::new(&grok_to_regex("%{USER:user.name}")).unwrap();
                if let Some(caps) = grok_re.captures(input) {
                    for name in grok_re.capture_names().flatten() {
                        if let Some(m) = caps.name(name) {
                            event.set(name, m.as_str())?;
                        }
                    }
                }
            }
        }
            Ok(())
        })();

        // TODO: conditional: ctx?.user?.name != null
        {
        event.set("source.user.name", event.get("user.name").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx?.user?.name != null
        {
        event.set("client.user.name", event.get("user.name").cloned().unwrap_or(Value::Null))?;
        }

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.actor.displayName") {
                event.rename("json.actor.displayName", "okta.actor.display_name")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.actor.id") {
                event.rename("json.actor.id", "okta.actor.id")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.actor.type") {
                event.rename("json.actor.type", "okta.actor.type")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.client.device") {
                event.rename("json.client.device", "okta.client.device")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.device") {
                event.rename("json.device", "okta.device")?;
            }
            Ok(())
        })();

        // TODO: conditional: ctx.okta?.device?.device_integrator != null
        {
            if let Some(s) = event.get_str("okta.device.device_integrator").map(String::from) {
            let s = s.as_str();
                let parsed: Value = serde_json::from_str(s)
                    .map_err(|e| TransformError::ParseError {
                        path: "okta.device.device_integrator".into(),
                        message: format!("failed to parse JSON: {}", e),
                    })?;
                event.set("okta.device.device_integrator", parsed)?;
            }
        }

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.client.geographicalContext.geolocation") {
                event.rename("json.client.geographicalContext.geolocation", "client.geo.location")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.client.geographicalContext.city") {
                event.rename("json.client.geographicalContext.city", "client.geo.city_name")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.client.geographicalContext.state") {
                event.rename("json.client.geographicalContext.state", "client.geo.region_name")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.client.geographicalContext.country") {
                event.rename("json.client.geographicalContext.country", "client.geo.country_name")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.client.id") {
                event.rename("json.client.id", "okta.client.id")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
        if event.has("json.client.ipAddress") {
            if let Some(s) = event.get_str("json.client.ipAddress").map(String::from) {
            let s = s.as_str();
                // Validate IP format
                let s = s.trim();
                if s.parse::<std::net::IpAddr>().is_err() {
                    return Err(TransformError::ParseError { path: "json.client.ipAddress".into(), message: format!("cannot convert '{}' to IP", s) }.into());
                }
                event.set("okta.client.ip", s)?;
            }
        }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.client.userAgent.browser") {
                event.rename("json.client.userAgent.browser", "okta.client.user_agent.browser")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.client.userAgent.os") {
                event.rename("json.client.userAgent.os", "okta.client.user_agent.os")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.client.userAgent.rawUserAgent") {
                event.rename("json.client.userAgent.rawUserAgent", "okta.client.user_agent.raw_user_agent")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.client.zone") {
                event.rename("json.client.zone", "okta.client.zone")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.outcome.reason") {
                event.rename("json.outcome.reason", "okta.outcome.reason")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.outcome.result") {
                event.rename("json.outcome.result", "okta.outcome.result")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.target") {
                event.rename("json.target", "okta.target")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.transaction.id") {
                event.rename("json.transaction.id", "okta.transaction.id")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.transaction.type") {
                event.rename("json.transaction.type", "okta.transaction.type")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.transaction.detail.requestApiTokenId") {
                event.rename("json.transaction.detail.requestApiTokenId", "okta.transaction.detail.request_api_token_id")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
        event.set("okta.debug_context.debug_data.flattened", event.get("json.debugContext.debugData").cloned().unwrap_or(Value::Null))?;
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if let Some(s) = event.get_str("okta.debug_context.debug_data.flattened.logOnlySecurityData").map(String::from) {
            let s = s.as_str();
                let parsed: Value = serde_json::from_str(s)
                    .map_err(|e| TransformError::ParseError {
                        path: "okta.debug_context.debug_data.flattened.logOnlySecurityData".into(),
                        message: format!("failed to parse JSON: {}", e),
                    })?;
                event.set("okta.debug_context.debug_data.flattened.logOnlySecurityData", parsed)?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
        if event.has("okta.debug_context.debug_data.flattened.behaviors") {
            if let Some(input) = event.get_str("okta.debug_context.debug_data.flattened.behaviors").map(String::from) {
            let input = input.as_str();
                let mut remaining = input;
                if let Some(rest) = remaining.strip_prefix("{") {
                    remaining = rest;
                }
                if let Some(pos) = remaining.find("}") {
                    event.set("okta.debug_context.debug_data.flattened.behaviors", &remaining[..pos])?;
                    remaining = &remaining[pos..];
                }
                if let Some(rest) = remaining.strip_prefix("}") {
                    remaining = rest;
                }
            }
        }
            Ok(())
        })();

        // TODO: conditional: ctx.okta?.debug_context?.debug_data?.flattened?.behaviors != null
        {
            if let Some(kv_str) = event.get_str("okta.debug_context.debug_data.flattened.behaviors").map(String::from) {
            let kv_str = kv_str.as_str();
                for pair in kv_str.split(", ") {
                    if let Some((key, value)) = pair.split_once("=") {
                        if !key.is_empty() {
                            event.set(&format!("_behaviors_object.{}", key), value)?;
                        }
                    }
                }
            }
        }

        // TODO: conditional: ctx._behaviors_object != null
        {
            event.remove("okta.debug_context.debug_data.flattened.behaviors");
        }

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("_behaviors_object") {
                event.rename("_behaviors_object", "okta.debug_context.debug_data.flattened.behaviors")?;
            }
            Ok(())
        })();

        // TODO: conditional: ctx.okta?.debug_context?.debug_data?.flattened?.risk != null
        {
        event.set("okta.debug_context.debug_data.flattened.risk_object", event.get("okta.debug_context.debug_data.flattened.risk").cloned().unwrap_or(Value::Null))?;
        }

        // ignore_failure: true
        let _ = (|| -> Result<()> {
        if event.has("okta.debug_context.debug_data.flattened.risk") {
            if let Some(input) = event.get_str("okta.debug_context.debug_data.flattened.risk").map(String::from) {
            let input = input.as_str();
                let mut remaining = input;
                if let Some(rest) = remaining.strip_prefix("{") {
                    remaining = rest;
                }
                if let Some(pos) = remaining.find("}") {
                    event.set("okta.debug_context.debug_data.flattened.risk", &remaining[..pos])?;
                    remaining = &remaining[pos..];
                }
                if let Some(rest) = remaining.strip_prefix("}") {
                    remaining = rest;
                }
            }
        }
            Ok(())
        })();

        // TODO: conditional: ctx.okta?.debug_context?.debug_data?.flattened?.risk != null
        {
            if let Some(kv_str) = event.get_str("okta.debug_context.debug_data.flattened.risk").map(String::from) {
            let kv_str = kv_str.as_str();
                for pair in kv_str.split(", ") {
                    if let Some((key, value)) = pair.split_once("=") {
                        if !key.is_empty() {
                            event.set(&format!("_risk_object.{}", key), value)?;
                        }
                    }
                }
            }
        }

        // TODO: conditional: ctx._risk_object != null
        {
            event.remove("okta.debug_context.debug_data.flattened.risk_object");
        }

        // TODO: conditional: ctx.okta?.debug_context?.debug_data?.flattened?.risk_object != null && ctx.okta?.debug_context?.debug_data?.flattened?.risk != null
        {
        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if let Some(input) = event.get_str("okta.debug_context.debug_data.flattened.risk").map(String::from) {
            let input = input.as_str();
                // Grok pattern: level=%{NOTSPACE:_risk_object.level}
                // TODO: Replace with dfe-parse Layer 1/2/3 calls after grok analyser (2.1.2)
                let grok_re = regex::Regex::new(&grok_to_regex("level=%{NOTSPACE:_risk_object.level}")).unwrap();
                if let Some(caps) = grok_re.captures(input) {
                    for name in grok_re.capture_names().flatten() {
                        if let Some(m) = caps.name(name) {
                            event.set(name, m.as_str())?;
                        }
                    }
                }
            }
            Ok(())
        })();
        }

        // TODO: conditional: ctx.okta?.debug_context?.debug_data?.flattened?.risk_object != null && ctx.okta?.debug_context?.debug_data?.flattened?.risk != null
        {
        // ignore_failure: true
        let _ = (|| -> Result<()> {
            // Pattern definitions for grok
            // KEY = %{NOTSPACE}=
            if let Some(input) = event.get_str("okta.debug_context.debug_data.flattened.risk").map(String::from) {
            let input = input.as_str();
                // Grok pattern: reasons=%{DATA:_risk_object.reasons}, %{KEY}
                // TODO: Replace with dfe-parse Layer 1/2/3 calls after grok analyser (2.1.2)
                let grok_re = regex::Regex::new(&grok_to_regex("reasons=%{DATA:_risk_object.reasons}, %{KEY}")).unwrap();
                if let Some(caps) = grok_re.captures(input) {
                    for name in grok_re.capture_names().flatten() {
                        if let Some(m) = caps.name(name) {
                            event.set(name, m.as_str())?;
                        }
                    }
                }
                // Additional grok pattern 1: reasons=%{DATA:_risk_object.reasons}$
            }
            Ok(())
        })();
        }

        // TODO: conditional: ctx._risk_object != null
        {
            event.remove("okta.debug_context.debug_data.flattened.risk");
        }

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("_risk_object") {
                event.rename("_risk_object", "okta.debug_context.debug_data.flattened.risk")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.debugContext.debugData.deviceFingerprint") {
                event.rename("json.debugContext.debugData.deviceFingerprint", "okta.debug_context.debug_data.device_fingerprint")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.debugContext.debugData.requestId") {
                event.rename("json.debugContext.debugData.requestId", "okta.debug_context.debug_data.request_id")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.debugContext.debugData.requestUri") {
                event.rename("json.debugContext.debugData.requestUri", "okta.debug_context.debug_data.request_uri")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.debugContext.debugData.threatSuspected") {
                event.rename("json.debugContext.debugData.threatSuspected", "okta.debug_context.debug_data.threat_suspected")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.debugContext.debugData.url") {
                event.rename("json.debugContext.debugData.url", "okta.debug_context.debug_data.url")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.debugContext.debugData.dtHash") {
                event.rename("json.debugContext.debugData.dtHash", "okta.debug_context.debug_data.dt_hash")?;
            }
            Ok(())
        })();

        // TODO: conditional: ctx.okta?.debug_context?.debug_data?.flattened?.logOnlySecurityData?.risk?.level != null && ctx.okta?.debug_context?.debug_data?.flattened?.logOnlySecurityData?.risk?.level != ""
        {
        event.set("okta.debug_context.debug_data.risk_level", event.get("okta.debug_context.debug_data.flattened.logOnlySecurityData.risk.level").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx.okta?.debug_context?.debug_data?.flattened?.logOnlySecurityData?.risk?.reasons != null && ctx.okta?.debug_context?.debug_data?.flattened?.logOnlySecurityData?.risk?.reasons != ""
        {
            if let Some(s) = event.get_str("okta.debug_context.debug_data.flattened.logOnlySecurityData.risk.reasons").map(String::from) {
            let s = s.as_str();
                let parts: Vec<Value> = s.split(",\\s*").map(|p| json!(p)).collect();
                event.set("okta.debug_context.debug_data.risk_reasons", Value::Array(parts))?;
            }
        }

        // TODO: conditional: ctx.okta?.debug_context?.debug_data?.risk_level == null && ctx.okta?.debug_context?.debug_data?.flattened?.risk?.level != null && ctx.okta?.debug_context?.debug_data?.flattened?.risk?.level != ""
        {
        event.set("okta.debug_context.debug_data.risk_level", event.get("okta.debug_context.debug_data.flattened.risk.level").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx.okta?.debug_context?.debug_data?.factor == null && ctx.okta?.debug_context?.debug_data?.flattened?.factor != null && ctx.okta?.debug_context?.debug_data?.flattened?.factor != ""
        {
        event.set("okta.debug_context.debug_data.factor", event.get("okta.debug_context.debug_data.flattened.factor").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx.okta?.debug_context?.debug_data?.risk_reasons == null && ctx.okta?.debug_context?.debug_data?.flattened?.risk?.reasons != null && ctx.okta?.debug_context?.debug_data?.flattened?.risk?.reasons != ""
        {
            if let Some(s) = event.get_str("okta.debug_context.debug_data.flattened.risk.reasons").map(String::from) {
            let s = s.as_str();
                let parts: Vec<Value> = s.split(",\\s*").map(|p| json!(p)).collect();
                event.set("okta.debug_context.debug_data.risk_reasons", Value::Array(parts))?;
            }
        }

            // Painless script
            // Source: def src = ctx.okta?.debug_context?.debug_data?.flattened?.behaviors;\nif (src == null) {\n  return;\n}\ndef dst = new ArrayList();\nfor (e in src.entrySet()) {\n  if (e != null && e.getValue() == \"POSITIVE\") {\n    dst.add(e.getKey());\n  }\n}\nif (dst.length != 0) {\n  ctx.okta.debug_context.debug_data['risk_behaviors'] = dst;\n}\n
            // TODO: Transpile Painless to Rust (2.2.3)
            painless_exec(event, r#"def src = ctx.okta?.debug_context?.debug_data?.flattened?.behaviors;\nif (src == null) {\n  return;\n}\ndef dst = new ArrayList();\nfor (e in src.entrySet()) {\n  if (e != null && e.getValue() == \"POSITIVE\") {\n    dst.add(e.getKey());\n  }\n}\nif (dst.length != 0) {\n  ctx.okta.debug_context.debug_data['risk_behaviors'] = dst;\n}\n"#)?;

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.authenticationContext.authenticationProvider") {
                event.rename("json.authenticationContext.authenticationProvider", "okta.authentication_context.authentication_provider")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.authenticationContext.authenticationStep") {
                event.rename("json.authenticationContext.authenticationStep", "okta.authentication_context.authentication_step")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.authenticationContext.credentialProvider") {
                event.rename("json.authenticationContext.credentialProvider", "okta.authentication_context.credential_provider")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.authenticationContext.credentialType") {
                event.rename("json.authenticationContext.credentialType", "okta.authentication_context.credential_type")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.authenticationContext.externalSessionId") {
                event.rename("json.authenticationContext.externalSessionId", "okta.authentication_context.external_session_id")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.authenticationContext.interface") {
                event.rename("json.authenticationContext.interface", "okta.authentication_context.authentication_provider")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.authenticationContext.issuer") {
                event.rename("json.authenticationContext.issuer", "okta.authentication_context.issuer")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.securityContext.asNumber") {
                event.rename("json.securityContext.asNumber", "okta.security_context.as.number")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.securityContext.asOrg") {
                event.rename("json.securityContext.asOrg", "okta.security_context.as.organization.name")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.securityContext.domain") {
                event.rename("json.securityContext.domain", "okta.security_context.domain")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.securityContext.isProxy") {
                event.rename("json.securityContext.isProxy", "okta.security_context.is_proxy")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.securityContext.isp") {
                event.rename("json.securityContext.isp", "okta.security_context.isp")?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("json.request.ipChain") {
                event.rename("json.request.ipChain", "okta.request.ip_chain")?;
            }
            Ok(())
        })();

        if event.has("okta.request.ip_chain") {
            if let Some(arr) = event.get("okta.request.ip_chain").cloned() {
                if let Value::Array(items) = arr {
                    for (idx, _item) in items.iter().enumerate() {
                        // Set _ingest._value for inner processor access
                        let item_path = format!("okta.request.ip_chain[{}]", idx);
                        // Inner processor operates on the element:
                        // ignore_failure: true
                        let _ = (|| -> Result<()> {
                        if event.has("_ingest._value.geographicalContext") {
                        event.rename("_ingest._value.geographicalContext", "_ingest._value.geographical_context")?;
                        }
                            Ok(())
                        })();
                    }
                }
            }
        }

        if event.has("okta.request.ip_chain") {
            if let Some(arr) = event.get("okta.request.ip_chain").cloned() {
                if let Value::Array(items) = arr {
                    for (idx, _item) in items.iter().enumerate() {
                        // Set _ingest._value for inner processor access
                        let item_path = format!("okta.request.ip_chain[{}]", idx);
                        // Inner processor operates on the element:
                        // ignore_failure: true
                        let _ = (|| -> Result<()> {
                        if event.has("_ingest._value.geographical_context.postalCode") {
                        event.rename("_ingest._value.geographical_context.postalCode", "_ingest._value.geographical_context.postal_code")?;
                        }
                            Ok(())
                        })();
                    }
                }
            }
        }

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if let Some(val) = event.get("okta.client.user_agent.raw_user_agent") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("user_agent.original", converted)?;
            }
            Ok(())
        })();

        // TODO: conditional: ctx?.okta?.client?.ip != null
        {
        event.set("client.ip", event.get("okta.client.ip").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx?.okta?.client?.ip != null
        {
        event.set("source.ip", event.get("okta.client.ip").cloned().unwrap_or(Value::Null))?;
        }

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if let Some(val) = event.get("okta.event_type") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("event.action", converted)?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if let Some(val) = event.get("okta.security_context.as.organization.name") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("client.as.organization.name", converted)?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if let Some(val) = event.get("okta.security_context.domain") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("client.domain", converted)?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if let Some(val) = event.get("okta.security_context.domain") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("source.domain", converted)?;
            }
            Ok(())
        })();

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if let Some(val) = event.get("okta.uuid") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("event.id", converted)?;
            }
            Ok(())
        })();

        if event.has("okta.outcome.result") {
            if let Some(s) = event.get_str("okta.outcome.result").map(String::from) {
            let s = s.as_str();
                let lowered = s.to_lowercase();
                event.set("okta.outcome.result_lower", lowered)?;
            }
        }

        // TODO: conditional: ctx?.okta?.outcome?.result_lower != null && (ctx?.okta?.outcome?.result_lower == "success" || ctx?.okta?.outcome?.result_lower == "allow")
        {
        event.set("event.outcome", json!("success"))?;
        }

        // TODO: conditional: ctx?.okta?.outcome?.result_lower != null && (ctx?.okta?.outcome?.result_lower == "failure" || ctx?.okta?.outcome?.result_lower == "deny")
        {
        event.set("event.outcome", json!("failure"))?;
        }

        // TODO: conditional: ctx?.event?.outcome == null
        {
        event.set("event.outcome", json!("unknown"))?;
        }

            event.remove("okta.outcome.result_lower");

            // Painless script
            // Source: def arr = ctx.okta?.target;\nif (arr != null) {\n  for (def i = 0; i < arr.length; i++) {\n    arr[i][\"alternate_id\"] = arr[i][\"alternateId\"];\n    arr[i].remove(\"alternateId\");\n    arr[i][\"display_name\"] = arr[i][\"displayName\"];\n    arr[i].remove(\"displayName\");\n    def de = arr[i].get(\"detailEntry\");\n    if (de != null) {\n      de.entrySet().removeIf(entry -> \n        entry.getKey() != \"methodTypeUsed\" && \n        entry.getKey() != \"methodUsedVerifiedProperties\");\n      if (de.size() == 0) {\n        arr[i].remove(\"detailEntry\");\n      }\n    }\n  }\n\n  for (def i = 0; i < arr.length; i++) {\n    if (arr[i][\"type\"].toLowerCase() == \"user\") {\n      ctx[\"okta_target_user\"] = arr[i];\n      break;\n    }\n  }\n\n  for (def i = 0; i < arr.length; i++) {\n    if (arr[i][\"type\"].toLowerCase() == \"usergroup\") {\n      ctx[\"okta_target_group\"] = arr[i];\n      break;\n    }\n  }\n}\n
            // TODO: Transpile Painless to Rust (2.2.3)
            painless_exec(event, r#"def arr = ctx.okta?.target;\nif (arr != null) {\n  for (def i = 0; i < arr.length; i++) {\n    arr[i][\"alternate_id\"] = arr[i][\"alternateId\"];\n    arr[i].remove(\"alternateId\");\n    arr[i][\"display_name\"] = arr[i][\"displayName\"];\n    arr[i].remove(\"displayName\");\n    def de = arr[i].get(\"detailEntry\");\n    if (de != null) {\n      de.entrySet().removeIf(entry -> \n        entry.getKey() != \"methodTypeUsed\" && \n        entry.getKey() != \"methodUsedVerifiedProperties\");\n      if (de.size() == 0) {\n        arr[i].remove(\"detailEntry\");\n      }\n    }\n  }\n\n  for (def i = 0; i < arr.length; i++) {\n    if (arr[i][\"type\"].toLowerCase() == \"user\") {\n      ctx[\"okta_target_user\"] = arr[i];\n      break;\n    }\n  }\n\n  for (def i = 0; i < arr.length; i++) {\n    if (arr[i][\"type\"].toLowerCase() == \"usergroup\") {\n      ctx[\"okta_target_group\"] = arr[i];\n      break;\n    }\n  }\n}\n"#)?;

        // TODO: conditional: ctx.okta_target_user?.display_name != null
        {
        event.set("user.target.full_name", event.get("okta_target_user.display_name").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx.okta_target_user?.id != null
        {
        event.set("user.target.id", event.get("okta_target_user.id").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx.okta_target_user?.login != null
        {
        event.set("user.target.email", event.get("okta_target_user.login").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx.okta_target_group?.display_name != null
        {
        event.set("user.target.group.name", event.get("okta_target_group.display_name").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx.okta_target_group?.id != null
        {
        event.set("user.target.group.id", event.get("okta_target_group.id").cloned().unwrap_or(Value::Null))?;
        }

            event.remove("okta_target_user");
            event.remove("okta_target_group");

        // TODO: conditional: ctx?.okta?.actor?.id != null
        {
        event.set("client.user.id", event.get("okta.actor.id").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx?.okta?.actor?.id != null
        {
        event.set("source.user.id", event.get("okta.actor.id").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx?.okta?.actor?.display_name != null
        {
        event.set("client.user.full_name", event.get("okta.actor.display_name").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx?.okta?.actor?.display_name != null
        {
        event.set("source.user.full_name", event.get("okta.actor.display_name").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx?.okta?.actor?.display_name != null
        {
        event.set("user.full_name", event.get("okta.actor.display_name").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx?.okta?.actor?.display_name != null
        {
            event.append("related.user", event.get("okta.actor.display_name").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx?.user?.target?.full_name != null
        {
            event.append("related.user", event.get("user.target.full_name").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx?.user?.name != null
        {
            event.append("related.user", event.get("user.name").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx?.source?.ip != null
        {
            event.append("related.ip", event.get("source.ip").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx?.destination?.ip != null
        {
            event.append("related.ip", event.get("destination.ip").cloned().unwrap_or(Value::Null))?;
        }

            event.remove("json");

        if event.has("user_agent.original") {
            if let Some(ua_str) = event.get_str("user_agent.original").map(String::from) {
            let ua_str = ua_str.as_str();
                let ua_str = ua_str.to_string();
                // User agent parsing
                if let Ok(ua) = parse_user_agent(&ua_str) {
                    event.set("user_agent.original", json!(ua_str))?;
                    if let Some(name) = ua.name { event.set("user_agent.name", json!(name))?; }
                    if let Some(version) = ua.version { event.set("user_agent.version", json!(version))?; }
                    if let Some(os_name) = ua.os_name {
                        event.set("user_agent.os.name", json!(os_name))?;
                        if let Some(os_version) = ua.os_version {
                            event.set("user_agent.os.version", json!(os_version))?;
                            event.set("user_agent.os.full", json!(format!("{} {}", os_name, os_version)))?;
                        }
                    }
                    if let Some(device) = ua.device { event.set("user_agent.device.name", json!(device))?; }
                }
            }
        }

        if event.has("source.ip") {
            if let Some(ip_str) = event.get_str("source.ip").map(String::from) {
            let ip_str = ip_str.as_str();
                let ip_str = ip_str.to_string();
                // GeoIP enrichment (GeoLite2-City.mmdb)
                if let Ok(geo) = geoip_lookup("geoip_city", &ip_str) {
                    if let Some(v) = geo.get("country_iso_code") {
                        event.set("source.geo.country_iso_code", v.clone())?;
                    }
                    if let Some(v) = geo.get("country_name") {
                        event.set("source.geo.country_name", v.clone())?;
                    }
                    if let Some(v) = geo.get("continent_name") {
                        event.set("source.geo.continent_name", v.clone())?;
                    }
                    if let Some(v) = geo.get("region_iso_code") {
                        event.set("source.geo.region_iso_code", v.clone())?;
                    }
                    if let Some(v) = geo.get("region_name") {
                        event.set("source.geo.region_name", v.clone())?;
                    }
                    if let Some(v) = geo.get("city_name") {
                        event.set("source.geo.city_name", v.clone())?;
                    }
                    if let Some(v) = geo.get("timezone") {
                        event.set("source.geo.timezone", v.clone())?;
                    }
                    if let Some(v) = geo.get("location") {
                        event.set("source.geo.location", v.clone())?;
                    }
                }
            }
        }

        if event.has("destination.ip") {
            if let Some(ip_str) = event.get_str("destination.ip").map(String::from) {
            let ip_str = ip_str.as_str();
                let ip_str = ip_str.to_string();
                // GeoIP enrichment (GeoLite2-City.mmdb)
                if let Ok(geo) = geoip_lookup("geoip_city", &ip_str) {
                    if let Some(v) = geo.get("country_iso_code") {
                        event.set("destination.geo.country_iso_code", v.clone())?;
                    }
                    if let Some(v) = geo.get("country_name") {
                        event.set("destination.geo.country_name", v.clone())?;
                    }
                    if let Some(v) = geo.get("continent_name") {
                        event.set("destination.geo.continent_name", v.clone())?;
                    }
                    if let Some(v) = geo.get("region_iso_code") {
                        event.set("destination.geo.region_iso_code", v.clone())?;
                    }
                    if let Some(v) = geo.get("region_name") {
                        event.set("destination.geo.region_name", v.clone())?;
                    }
                    if let Some(v) = geo.get("city_name") {
                        event.set("destination.geo.city_name", v.clone())?;
                    }
                    if let Some(v) = geo.get("timezone") {
                        event.set("destination.geo.timezone", v.clone())?;
                    }
                    if let Some(v) = geo.get("location") {
                        event.set("destination.geo.location", v.clone())?;
                    }
                }
            }
        }

        if event.has("source.ip") {
            if let Some(ip_str) = event.get_str("source.ip").map(String::from) {
            let ip_str = ip_str.as_str();
                let ip_str = ip_str.to_string();
                // GeoIP enrichment (GeoLite2-ASN.mmdb)
                if let Ok(geo) = geoip_lookup("geoip_asn", &ip_str) {
                    if let Some(v) = geo.get("asn") {
                        event.set("source.as.asn", v.clone())?;
                    }
                    if let Some(v) = geo.get("organization_name") {
                        event.set("source.as.organization_name", v.clone())?;
                    }
                }
            }
        }

        if event.has("destination.ip") {
            if let Some(ip_str) = event.get_str("destination.ip").map(String::from) {
            let ip_str = ip_str.as_str();
                let ip_str = ip_str.to_string();
                // GeoIP enrichment (GeoLite2-ASN.mmdb)
                if let Ok(geo) = geoip_lookup("geoip_asn", &ip_str) {
                    if let Some(v) = geo.get("asn") {
                        event.set("destination.as.asn", v.clone())?;
                    }
                    if let Some(v) = geo.get("organization_name") {
                        event.set("destination.as.organization_name", v.clone())?;
                    }
                }
            }
        }

            if event.has("source.as.asn") {
                event.rename("source.as.asn", "source.as.number")?;
            }

            if event.has("source.as.organization_name") {
                event.rename("source.as.organization_name", "source.as.organization.name")?;
            }

            if event.has("destination.as.asn") {
                event.rename("destination.as.asn", "destination.as.number")?;
            }

            if event.has("destination.as.organization_name") {
                event.rename("destination.as.organization_name", "destination.as.organization.name")?;
            }

        // TODO: conditional: ctx?.tags == null || !(ctx.tags.contains('preserve_original_event'))
        {
        // ignore_failure: true
        let _ = (|| -> Result<()> {
            event.remove("event.original");
            Ok(())
        })();
        }

        Ok(TransformResult::Continue)
    }
}
