apiVersion: v2
name: dfe-transform-elastic
description: Beats and Elastic Agent JSON in, DFE-normalised events out
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - dfe-transform-elastic
