[package]
name = "dfe-codegen"
description = "Elastic ingest pipeline to Rust code generator (elastic_to_rust)"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "dfe-codegen"
path = "src/main.rs"

[dependencies]
antlr-rust = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
gtmpl = { workspace = true }
regex = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
scalo = { workspace = true }
clap = { workspace = true }
lazy_static = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
paste = { workspace = true }
syn = { workspace = true }
