apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dfe-transform-elastic.fullname" . }}-config
  labels:
    {{- include "dfe-transform-elastic.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
