{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "dfe-transform-elastic.fullname" . }}-kafka-auth
  labels:
    {{- include "dfe-transform-elastic.labels" . | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: sasl
      name: {{ include "dfe-transform-elastic.kafkaSecretName" . }}
      key: {{ .Values.kafka.secretKeys.username }}
    - parameter: password
      name: {{ include "dfe-transform-elastic.kafkaSecretName" . }}
      key: {{ .Values.kafka.secretKeys.password }}
{{- end }}
