// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 HYPERI PTY LIMITED
//
// Generated by dfe-codegen. Do not edit.

use dfe_runtime::prelude::*;

/// Transform for the `auth_activity_audit` pipeline.
pub struct AuthActivityAudit;

impl Transform for AuthActivityAudit {
    fn name(&self) -> &str {
        "auth_activity_audit"
    }

    fn transform(&self, event: &mut Event) -> Result<TransformResult> {
        event.set("event.kind", json!("event"))?;

        // TODO: conditional: ctx.crowdstrike?.event?.OperationName != null && !["twoFactorAuthenticate", "userAuthenticate"].contains(ctx.crowdstrike.event.OperationName)
        {
            event.append("event.category", json!("iam"))?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.OperationName != null && ["twoFactorAuthenticate", "userAuthenticate"].contains(ctx.crowdstrike.event.OperationName)
        {
            event.append("event.category", json!("authentication"))?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.OperationName != null && ["activateUser", "changePassword", "confirmResetPassword", "deactivateUser", "grantUserRoles", "grantCustomerSubscriptions", "revokeUserRoles", "revokeCustomerSubscriptions", "updateUser", "updateUserRoles"].contains(ctx.crowdstrike.event.OperationName)
        {
            event.append("event.type", json!("user"))?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.OperationName != null && ["activateUser", "changePassword", "confirmResetPassword", "deactivateUser", "grantUserRoles", "grantCustomerSubscriptions", "revokeUserRoles", "revokeCustomerSubscriptions", "updateUser", "updateUserRoles"].contains(ctx.crowdstrike.event.OperationName)
        {
            event.append("event.type", json!("change"))?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.OperationName != null && ctx.crowdstrike.event.OperationName == "createUser"
        {
            event.append("event.type", json!("creation"))?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.OperationName != null && ctx.crowdstrike.event.OperationName == "deleteUser"
        {
            event.append("event.type", json!("deletion"))?;
        }

        if event.has("crowdstrike.event.UserId") {
            event.rename("crowdstrike.event.UserId", "user.name")?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.OperationName != null
        {
            event.append(
                "event.action",
                event
                    .get("crowdstrike.event.OperationName")
                    .cloned()
                    .unwrap_or(Value::Null),
            )?;
        }

        // TODO: conditional: ctx.event?.action == null
        {
            event.append("event.action", json!("AuthActivityAuditEvent"))?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.Success == true
        {
            event.set("event.outcome", json!("success"))?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.Success == false
        {
            event.set("event.outcome", json!("failure"))?;
        }

        // TODO: conditional: ctx.event?.outcome == null
        {
            event.set("event.outcome", json!("unknown"))?;
        }

        if event.has("crowdstrike.event.ServiceName") {
            event.rename("crowdstrike.event.ServiceName", "message")?;
        }

        if event.has("crowdstrike.event.UserIp") {
            event.rename("crowdstrike.event.UserIp", "source.ip")?;
        }

        Ok(TransformResult::Continue)
    }
}
