// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 HYPERI PTY LIMITED
//
// Generated by dfe-codegen. Do not edit.

use dfe_runtime::prelude::*;

/// Transform for the `cspm_events` pipeline.
pub struct CspmEvents;

impl Transform for CspmEvents {
    fn name(&self) -> &str {
        "cspm_events"
    }

    fn transform(&self, event: &mut Event) -> Result<TransformResult> {
        event.set("event.kind", json!("alert"))?;

            event.append("event.category", json!("configuration"))?;

            event.append("event.type", json!("info"))?;
            event.append("event.type", json!("change"))?;

        let _cond = { event.get_str("crowdstrike.event.Disposition") == Some("Passed") };
        if _cond {
        event.set("event.outcome", json!("success"))?;
        }

        let _cond = { event.get_str("crowdstrike.event.Disposition") == Some("Failed") };
        if _cond {
        event.set("event.outcome", json!("failure"))?;
        }

            if event.has("crowdstrike.event.EventAction") {
                event.rename("crowdstrike.event.EventAction", "event.action")?;
            }

            if event.has("crowdstrike.event.ReportUrl") {
                event.rename("crowdstrike.event.ReportUrl", "event.reference")?;
            }

        let _cond = { event.has("crowdstrike.event.ResourceAttributes") };
        if _cond {
            if let Some(s) = event.get_string("crowdstrike.event.ResourceAttributes") {
                let parsed: Value = serde_json::from_str(&s)
                    .map_err(|e| TransformError::ParseError {
                        path: "crowdstrike.event.ResourceAttributes".into(),
                        message: format!("failed to parse JSON: {}", e),
                    })?;
                event.set("crowdstrike.event.ResourceAttributes", parsed)?;
            }
        }

            if event.has("crowdstrike.event.EventSource") {
                event.rename("crowdstrike.event.EventSource", "event.provider")?;
            }

            if event.has("crowdstrike.event.Severity") {
                event.rename("crowdstrike.event.Severity", "event.severity")?;
            }

        let _cond = { !event.has("cloud.account.id") };
        if _cond {
            if event.has("crowdstrike.event.AccountId") {
                event.rename("crowdstrike.event.AccountId", "cloud.account.id")?;
            }
        }

        let _cond = { !event.has("cloud.region") };
        if _cond {
            if event.has("crowdstrike.event.Region") {
                event.rename("crowdstrike.event.Region", "cloud.region")?;
            }
        }

        let _cond = { !event.has("cloud.provider") };
        if _cond {
            if event.has("crowdstrike.event.CloudProvider") {
                event.rename("crowdstrike.event.CloudProvider", "cloud.provider")?;
            }
        }

        let _cond = { !event.has("cloud.provider") };
        if _cond {
            if event.has("crowdstrike.event.CloudPlatform") {
                event.rename("crowdstrike.event.CloudPlatform", "cloud.provider")?;
            }
        }

        let _cond = { !event.has("cloud.service.name") };
        if _cond {
            if event.has("crowdstrike.event.CloudService") {
                event.rename("crowdstrike.event.CloudService", "cloud.service.name")?;
            }
        }

            if event.has("crowdstrike.event.PolicyStatement") {
                event.rename("crowdstrike.event.PolicyStatement", "message")?;
            }

            if event.has("crowdstrike.event.UserName") {
                event.rename("crowdstrike.event.UserName", "user.name")?;
            }

            if event.has("crowdstrike.event.UserId") {
                event.rename("crowdstrike.event.UserId", "user.id")?;
            }

            if event.has("crowdstrike.event.UserSourceIp") {
                event.rename("crowdstrike.event.UserSourceIp", "source.ip")?;
            }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.Timestamp != null && String.valueOf(ctx.crowdstrike.event.Timestamp).length() >= 12
        {
            if let Some(date_str) = event.get_string("crowdstrike.event.Timestamp") {
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("@timestamp", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.Timestamp != null && String.valueOf(ctx.crowdstrike.event.Timestamp).length() <= 11
        {
            if let Some(date_str) = event.get_string("crowdstrike.event.Timestamp") {
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("@timestamp", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.EventCreatedTimestamp != null && String.valueOf(ctx.crowdstrike.event.EventCreatedTimestamp).length() >= 12
        {
            if let Some(date_str) = event.get_string("crowdstrike.event.EventCreatedTimestamp") {
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("@timestamp", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.EventCreatedTimestamp != null && String.valueOf(ctx.crowdstrike.event.EventCreatedTimestamp).length() <= 11
        {
            if let Some(date_str) = event.get_string("crowdstrike.event.EventCreatedTimestamp") {
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("@timestamp", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.ResourceCreateTime != null && ctx.crowdstrike.event.ResourceCreateTime == 0
        {
            event.remove("crowdstrike.event.ResourceCreateTime");
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.ResourceCreateTime != null && ctx.crowdstrike.event.ResourceCreateTime != 0 && String.valueOf(ctx.crowdstrike.event.ResourceCreateTime).length() >= 12
        {
            if let Some(date_str) = event.get_string("crowdstrike.event.ResourceCreateTime") {
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("crowdstrike.event.ResourceCreateTime", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.ResourceCreateTime != null && ctx.crowdstrike.event.ResourceCreateTime != 0 && String.valueOf(ctx.crowdstrike.event.ResourceCreateTime).length() <= 11
        {
            if let Some(date_str) = event.get_string("crowdstrike.event.ResourceCreateTime") {
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("crowdstrike.event.ResourceCreateTime", dt.to_rfc3339())?;
                    }
                }
            }
        }

        let _cond = { event.has("crowdstrike.event.Tactic") };
        if _cond {
            event.append("threat.tactic.name", event.get("crowdstrike.event.Tactic").cloned().unwrap_or(Value::Null))?;
        }

        let _cond = { event.has("crowdstrike.event.Technique") };
        if _cond {
            event.append("threat.technique.name", event.get("crowdstrike.event.Technique").cloned().unwrap_or(Value::Null))?;
        }

        Ok(TransformResult::Continue)
    }
}
