// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 HYPERI PTY LIMITED
//
// Generated by dfe-codegen. Do not edit.

use dfe_runtime::prelude::*;

/// Transform for the `identity_protection_incident` pipeline.
pub struct IdentityProtectionIncident;

impl Transform for IdentityProtectionIncident {
    fn name(&self) -> &str {
        "identity_protection_incident"
    }

    fn transform(&self, event: &mut Event) -> Result<TransformResult> {
        event.set("event.kind", json!("event"))?;

        event.append("event.category", json!("iam"))?;

        event.append("event.type", json!("info"))?;

        if event.has("crowdstrike.event.IncidentType") {
            event.rename("crowdstrike.event.IncidentType", "event.action")?;
        }

        if event.has("crowdstrike.event.IncidentDescription") {
            event.rename("crowdstrike.event.IncidentDescription", "message")?;
        }

        if event.has("crowdstrike.event.Severity") {
            event.rename("crowdstrike.event.Severity", "event.severity")?;
        }

        if event.has("crowdstrike.event.IdentityProtectionIncidentId") {
            event.rename("crowdstrike.event.IdentityProtectionIncidentId", "event.id")?;
        }

        if event.has("crowdstrike.event.FalconHostLink") {
            event.rename("crowdstrike.event.FalconHostLink", "event.reference")?;
        }

        if event.has("crowdstrike.event.UserName") {
            event.rename("crowdstrike.event.UserName", "user.name")?;
        }

        // TODO: conditional not transpiled: ctx.user?.name != null && ctx.user.name.contains('\\')
        {
            if let Some(input) = event.get_string("user.name") {
                let mut remaining: &str = &input;
                if let Some(pos) = remaining.find("\\") {
                    event.set("user.domain", &remaining[..pos])?;
                    remaining = &remaining[pos..];
                }
                if let Some(rest) = remaining.strip_prefix("\\") {
                    remaining = rest;
                }
                event.set("user.name", remaining)?;
            }
        }

        if event.has("crowdstrike.event.EndpointName") {
            event.rename("crowdstrike.event.EndpointName", "host.hostname")?;
        }

        if event.has("crowdstrike.event.EndpointIp") {
            event.rename("crowdstrike.event.EndpointIp", "host.ip")?;
        }

        let _cond = { event.has("crowdstrike.event.StartTime") };
        if _cond {
            if event.has("crowdstrike.event.StartTime") {
                if let Some(val) = event.get("crowdstrike.event.StartTime") {
                    let converted = match val {
                        Value::String(_) => val.clone(),
                        Value::Number(n) => json!(n.to_string()),
                        Value::Bool(b) => json!(b.to_string()),
                        Value::Null => json!("null"),
                        _ => json!(val.to_string()),
                    };
                    event.set("crowdstrike.event.StartTime", converted)?;
                }
            }
        }

        let _cond = {
            event.has("crowdstrike.event.StartTime")
                && event
                    .get_as_string("crowdstrike.event.StartTime")
                    .is_some_and(|s| s.len() > 18)
        };
        if _cond {
            if let Some(s) = event.get_string("crowdstrike.event.StartTime") {
                let re = regex::Regex::new("\\d{6}$").unwrap();
                let replaced = re.replace_all(&s, "").into_owned();
                event.set("crowdstrike.event.StartTime", replaced)?;
            }
        }

        let _cond = {
            event.has("crowdstrike.event.StartTime")
                && event
                    .get_as_string("crowdstrike.event.StartTime")
                    .is_some_and(|s| s.len() >= 12)
        };
        if _cond {
            if let Some(date_str) = event.get_as_string("crowdstrike.event.StartTime") {
                // Try UNIX_MS timestamp (skip epoch 0)
                if let Ok(ms) = date_str.parse::<i64>() {
                    if ms > 0 {
                        if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                            event.set(
                                "event.start",
                                dt.format("%Y-%m-%dT%H:%M:%S%.3fZ").to_string(),
                            )?;
                        }
                    }
                }
            }
        }

        let _cond = {
            event.has("crowdstrike.event.StartTime")
                && event
                    .get_as_string("crowdstrike.event.StartTime")
                    .is_some_and(|s| s.len() <= 11)
        };
        if _cond {
            if let Some(date_str) = event.get_as_string("crowdstrike.event.StartTime") {
                // Try UNIX timestamp (skip epoch 0)
                if let Ok(ts) = date_str.parse::<f64>() {
                    if ts > 0.0 {
                        let secs = ts as i64;
                        let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                        if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                            event.set(
                                "event.start",
                                dt.format("%Y-%m-%dT%H:%M:%S%.3fZ").to_string(),
                            )?;
                        }
                    }
                }
            }
        }

        let _cond = { event.has("crowdstrike.event.EndTime") };
        if _cond {
            if event.has("crowdstrike.event.EndTime") {
                if let Some(val) = event.get("crowdstrike.event.EndTime") {
                    let converted = match val {
                        Value::String(_) => val.clone(),
                        Value::Number(n) => json!(n.to_string()),
                        Value::Bool(b) => json!(b.to_string()),
                        Value::Null => json!("null"),
                        _ => json!(val.to_string()),
                    };
                    event.set("crowdstrike.event.EndTime", converted)?;
                }
            }
        }

        let _cond = {
            event.has("crowdstrike.event.EndTime")
                && event
                    .get_as_string("crowdstrike.event.EndTime")
                    .is_some_and(|s| s.len() > 18)
        };
        if _cond {
            if let Some(s) = event.get_string("crowdstrike.event.EndTime") {
                let re = regex::Regex::new("\\d{6}$").unwrap();
                let replaced = re.replace_all(&s, "").into_owned();
                event.set("crowdstrike.event.EndTime", replaced)?;
            }
        }

        let _cond = {
            event.has("crowdstrike.event.EndTime")
                && event
                    .get_as_string("crowdstrike.event.EndTime")
                    .is_some_and(|s| s.len() >= 12)
        };
        if _cond {
            if let Some(date_str) = event.get_as_string("crowdstrike.event.EndTime") {
                // Try UNIX_MS timestamp (skip epoch 0)
                if let Ok(ms) = date_str.parse::<i64>() {
                    if ms > 0 {
                        if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                            event.set(
                                "event.start",
                                dt.format("%Y-%m-%dT%H:%M:%S%.3fZ").to_string(),
                            )?;
                        }
                    }
                }
            }
        }

        let _cond = {
            event.has("crowdstrike.event.EndTime")
                && event
                    .get_as_string("crowdstrike.event.EndTime")
                    .is_some_and(|s| s.len() <= 11)
        };
        if _cond {
            if let Some(date_str) = event.get_as_string("crowdstrike.event.EndTime") {
                // Try UNIX timestamp (skip epoch 0)
                if let Ok(ts) = date_str.parse::<f64>() {
                    if ts > 0.0 {
                        let secs = ts as i64;
                        let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                        if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                            event.set(
                                "event.start",
                                dt.format("%Y-%m-%dT%H:%M:%S%.3fZ").to_string(),
                            )?;
                        }
                    }
                }
            }
        }

        let _cond = { event.has("event.start") };
        if _cond {
            event.set(
                "@timestamp",
                event.get("event.start").cloned().unwrap_or(Value::Null),
            )?;
        }

        Ok(TransformResult::Continue)
    }
}
