// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 HYPERI PTY LIMITED
//
// Generated by dfe-codegen. Do not edit.

use dfe_runtime::prelude::*;

/// Transform for the `incident_summary` pipeline.
pub struct IncidentSummary;

impl Transform for IncidentSummary {
    fn name(&self) -> &str {
        "incident_summary"
    }

    fn transform(&self, event: &mut Event) -> Result<TransformResult> {
        event.set("event.kind", json!("alert"))?;

            event.append("event.category", json!("malware"))?;

            event.append("event.type", json!("info"))?;

            event.append("event.action", json!("incident"))?;

            if event.has("crowdstrike.event.UserId") {
                event.rename("crowdstrike.event.UserId", "user.name")?;
            }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.IncidentStartTime != null && String.valueOf(ctx.crowdstrike.event.IncidentStartTime).length() >= 12
        {
            if let Some(date_str) = event.get_string("crowdstrike.event.IncidentStartTime") {
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("event.start", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.IncidentStartTime != null && String.valueOf(ctx.crowdstrike.event.IncidentStartTime).length() <= 11
        {
            if let Some(date_str) = event.get_string("crowdstrike.event.IncidentStartTime") {
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("event.start", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.IncidentEndTime != null && String.valueOf(ctx.crowdstrike.event.IncidentEndTime).length() >= 12
        {
            if let Some(date_str) = event.get_string("crowdstrike.event.IncidentEndTime") {
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("event.end", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.IncidentEndTime != null && String.valueOf(ctx.crowdstrike.event.IncidentEndTime).length() <= 11
        {
            if let Some(date_str) = event.get_string("crowdstrike.event.IncidentEndTime") {
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("event.end", dt.to_rfc3339())?;
                    }
                }
            }
        }

            if event.has("crowdstrike.event.FalconHostLink") {
                event.rename("crowdstrike.event.FalconHostLink", "event.reference")?;
            }

            if event.has("crowdstrike.event.HostID") {
                event.rename("crowdstrike.event.HostID", "host.id")?;
            }

            if event.has("crowdstrike.event.IncidentID") {
                event.rename("crowdstrike.event.IncidentID", "event.id")?;
            }

        let _cond = { event.has("crowdstrike.event.FineScore") };
        if _cond {
        event.set("message", json!(format!("Incident score {}", event.get_str("crowdstrike.event.FineScore").unwrap_or(""))))?;
        }

        Ok(TransformResult::Continue)
    }
}
