// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 HYPERI PTY LIMITED
//
// Generated by dfe-codegen. Do not edit.

use dfe_runtime::prelude::*;

/// Transform for the `ipd_detection_summary` pipeline.
pub struct IpdDetectionSummary;

impl Transform for IpdDetectionSummary {
    fn name(&self) -> &str {
        "ipd_detection_summary"
    }

    fn transform(&self, event: &mut Event) -> Result<TransformResult> {
        event.set("event.kind", json!("alert"))?;

            event.append("event.category", json!("malware"))?;

            event.append("event.type", json!("info"))?;

        event.set("event.action", json!("ipd-detection"))?;

        let _cond = { event.get_bool("crowdstrike.event.AttemptOutcome") == Some(true) };
        if _cond {
        event.set("event.outcome", json!("success"))?;
        }

        let _cond = { event.get_bool("crowdstrike.event.AttemptOutcome") == Some(false) };
        if _cond {
        event.set("event.outcome", json!("failure"))?;
        }

            if event.has("crowdstrike.event.DetectDescription") {
                event.rename("crowdstrike.event.DetectDescription", "message")?;
            }

            if event.has("crowdstrike.event.LocationCountryCode") {
                event.rename("crowdstrike.event.LocationCountryCode", "host.geo.country_iso_code")?;
            }

        if event.has("crowdstrike.event.PatternId") {
            if let Some(val) = event.get("crowdstrike.event.PatternId") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("rule.uuid", converted)?;
            }
        }

            if event.has("crowdstrike.event.Severity") {
                event.rename("crowdstrike.event.Severity", "event.severity")?;
            }

            if event.has("crowdstrike.event.SourceAccountDomain") {
                event.rename("crowdstrike.event.SourceAccountDomain", "user.domain")?;
            }

            if event.has("crowdstrike.event.SourceAccountName") {
                event.rename("crowdstrike.event.SourceAccountName", "user.name")?;
            }

            if event.has("crowdstrike.event.SourceAccountObjectSid") {
                event.rename("crowdstrike.event.SourceAccountObjectSid", "user.id")?;
            }

            if event.has("crowdstrike.event.SourceEndpointHostName") {
                event.rename("crowdstrike.event.SourceEndpointHostName", "host.name")?;
            }

            if event.has("crowdstrike.event.SourceEndpointIpAddress") {
                event.rename("crowdstrike.event.SourceEndpointIpAddress", "host.ip")?;
            }

        let _cond = { event.has("crowdstrike.event.Technique") };
        if _cond {
            event.append("threat.technique.name", event.get("crowdstrike.event.Technique").cloned().unwrap_or(Value::Null))?;
        }

        let _cond = { event.has("crowdstrike.event.TechniqueId") };
        if _cond {
            event.append("threat.technique.id", event.get("crowdstrike.event.TechniqueId").cloned().unwrap_or(Value::Null))?;
        }

        let _cond = { event.has("crowdstrike.event.Tactic") };
        if _cond {
            event.append("threat.tactic.name", event.get("crowdstrike.event.Tactic").cloned().unwrap_or(Value::Null))?;
        }

        let _cond = { event.has("crowdstrike.event.TacticId") };
        if _cond {
            event.append("threat.tactic.id", event.get("crowdstrike.event.TacticId").cloned().unwrap_or(Value::Null))?;
        }

        let _cond = { event.has("message") };
        if _cond {
        event.set("rule.description", event.get("message").cloned().unwrap_or(Value::Null))?;
        }

            if event.has("crowdstrike.event.DetectName") {
                event.rename("crowdstrike.event.DetectName", "rule.name")?;
            }

            if event.has("crowdstrike.event.DetectId") {
                event.rename("crowdstrike.event.DetectId", "rule.id")?;
            }

            if event.has("crowdstrike.event.FalconHostLink") {
                event.rename("crowdstrike.event.FalconHostLink", "event.reference")?;
            }

        let _cond = { event.has("crowdstrike.event.ContextTimeStamp") };
        if _cond {
            event.remove("event.created");
        }

        let _cond = { event.has("crowdstrike.event.ContextTimeStamp") };
        if _cond {
        if event.has("crowdstrike.event.ContextTimeStamp") {
            if let Some(val) = event.get("crowdstrike.event.ContextTimeStamp") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("crowdstrike.event.ContextTimeStamp", converted)?;
            }
        }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.ContextTimeStamp != null && ctx.crowdstrike.event.ContextTimeStamp.length() > 18
        {
            if let Some(s) = event.get_string("crowdstrike.event.ContextTimeStamp") {
                let re = regex::Regex::new("\\d{6}$").unwrap();
                let replaced = re.replace_all(&s, "").into_owned();
                event.set("crowdstrike.event.ContextTimeStamp", replaced)?;
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.ContextTimeStamp != null && ctx.crowdstrike.event.ContextTimeStamp.length() >= 12
        {
            if let Some(date_str) = event.get_as_string("crowdstrike.event.ContextTimeStamp") {
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("event.created", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.ContextTimeStamp != null && ctx.crowdstrike.event.ContextTimeStamp.length() <= 11
        {
            if let Some(date_str) = event.get_as_string("crowdstrike.event.ContextTimeStamp") {
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("event.created", dt.to_rfc3339())?;
                    }
                }
            }
        }

        let _cond = { event.has("crowdstrike.event.AccountCreationTimeStamp") };
        if _cond {
        if event.has("crowdstrike.event.AccountCreationTimeStamp") {
            if let Some(val) = event.get("crowdstrike.event.AccountCreationTimeStamp") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("crowdstrike.event.AccountCreationTimeStamp", converted)?;
            }
        }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.AccountCreationTimeStamp != null && ctx.crowdstrike.event.AccountCreationTimeStamp.length() > 18
        {
            if let Some(s) = event.get_string("crowdstrike.event.AccountCreationTimeStamp") {
                let re = regex::Regex::new("\\d{6}$").unwrap();
                let replaced = re.replace_all(&s, "").into_owned();
                event.set("crowdstrike.event.AccountCreationTimeStamp", replaced)?;
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.AccountCreationTimeStamp != null && ctx.crowdstrike.event.AccountCreationTimeStamp.length() >= 12
        {
            if let Some(date_str) = event.get_as_string("crowdstrike.event.AccountCreationTimeStamp") {
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("crowdstrike.event.AccountCreationTimeStamp", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.AccountCreationTimeStamp != null && ctx.crowdstrike.event.AccountCreationTimeStamp.length() <= 11
        {
            if let Some(date_str) = event.get_as_string("crowdstrike.event.AccountCreationTimeStamp") {
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("crowdstrike.event.AccountCreationTimeStamp", dt.to_rfc3339())?;
                    }
                }
            }
        }

        let _cond = { event.has("crowdstrike.event.StartTime") };
        if _cond {
        if event.has("crowdstrike.event.StartTime") {
            if let Some(val) = event.get("crowdstrike.event.StartTime") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("crowdstrike.event.StartTime", converted)?;
            }
        }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.StartTime != null && ctx.crowdstrike.event.StartTime.length() > 18
        {
            if let Some(s) = event.get_string("crowdstrike.event.StartTime") {
                let re = regex::Regex::new("\\d{6}$").unwrap();
                let replaced = re.replace_all(&s, "").into_owned();
                event.set("crowdstrike.event.StartTime", replaced)?;
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.StartTime != null && ctx.crowdstrike.event.StartTime.length() >= 12
        {
            if let Some(date_str) = event.get_as_string("crowdstrike.event.StartTime") {
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("event.start", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.StartTime != null && ctx.crowdstrike.event.StartTime.length() <= 11
        {
            if let Some(date_str) = event.get_as_string("crowdstrike.event.StartTime") {
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("event.start", dt.to_rfc3339())?;
                    }
                }
            }
        }

        let _cond = { event.has("crowdstrike.event.EndTime") };
        if _cond {
        if event.has("crowdstrike.event.EndTime") {
            if let Some(val) = event.get("crowdstrike.event.EndTime") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("crowdstrike.event.EndTime", converted)?;
            }
        }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.EndTime != null && ctx.crowdstrike.event.EndTime.length() > 18
        {
            if let Some(s) = event.get_string("crowdstrike.event.EndTime") {
                let re = regex::Regex::new("\\d{6}$").unwrap();
                let replaced = re.replace_all(&s, "").into_owned();
                event.set("crowdstrike.event.EndTime", replaced)?;
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.EndTime != null && ctx.crowdstrike.event.EndTime.length() >= 12
        {
            if let Some(date_str) = event.get_as_string("crowdstrike.event.EndTime") {
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("event.end", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.EndTime != null && ctx.crowdstrike.event.EndTime.length() <= 11
        {
            if let Some(date_str) = event.get_as_string("crowdstrike.event.EndTime") {
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("event.end", dt.to_rfc3339())?;
                    }
                }
            }
        }

        let _cond = { event.has("crowdstrike.event.TargetEndpointHostName") };
        if _cond {
            event.append("related.hosts", event.get("crowdstrike.event.TargetEndpointHostName").cloned().unwrap_or(Value::Null))?;
        }

        let _cond = { event.has("crowdstrike.event.TargetDomain") };
        if _cond {
            event.append("related.hosts", event.get("crowdstrike.event.TargetDomain").cloned().unwrap_or(Value::Null))?;
        }

        let _cond = { event.has("crowdstrike.event.TargetAccountName") };
        if _cond {
            event.append("related.user", event.get("crowdstrike.event.TargetAccountName").cloned().unwrap_or(Value::Null))?;
        }

        let _cond = { event.has("crowdstrike.event.AdditionalAccountDomain") };
        if _cond {
            event.append("related.hosts", event.get("crowdstrike.event.AdditionalAccountDomain").cloned().unwrap_or(Value::Null))?;
        }

        let _cond = { event.has("crowdstrike.event.AdditionalAccountName") };
        if _cond {
            event.append("related.hosts", event.get("crowdstrike.event.AdditionalAccountName").cloned().unwrap_or(Value::Null))?;
        }

        let _cond = { event.has("crowdstrike.event.AdditionalEndpointHostName") };
        if _cond {
            event.append("related.hosts", event.get("crowdstrike.event.AdditionalEndpointHostName").cloned().unwrap_or(Value::Null))?;
        }

        let _cond = { event.has("crowdstrike.event.AdditionalEndpointIpAddress") };
        if _cond {
            event.append("related.ip", event.get("crowdstrike.event.AdditionalEndpointIpAddress").cloned().unwrap_or(Value::Null))?;
        }

        Ok(TransformResult::Continue)
    }
}
