// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 HYPERI PTY LIMITED
//
// Generated by dfe-codegen. Do not edit.

use dfe_runtime::prelude::*;

/// Transform for the `mobile_detection_summary` pipeline.
pub struct MobileDetectionSummary;

impl Transform for MobileDetectionSummary {
    fn name(&self) -> &str {
        "mobile_detection_summary"
    }

    fn transform(&self, event: &mut Event) -> Result<TransformResult> {
        event.set("event.kind", json!("alert"))?;

            event.append("event.category", json!("malware"))?;

            event.append("event.type", json!("info"))?;

        event.set("event.action", json!("mobile-detection"))?;

        // TODO: conditional: ctx.crowdstrike?.event?.ContextTimeStamp != null
        {
            event.remove("event.created");
        }

        // TODO: conditional: ctx.crowdstrike?.event?.ContextTimeStamp != null && String.valueOf(ctx.crowdstrike.event.ContextTimeStamp).length() <= 11
        {
            if let Some(date_str) = event.get_str("crowdstrike.event.ContextTimeStamp").map(String::from) {
            let date_str = date_str.as_str();
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("event.created", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional: ctx.crowdstrike?.event?.ContextTimeStamp != null && String.valueOf(ctx.crowdstrike.event.ContextTimeStamp).length() >= 12
        {
            if let Some(date_str) = event.get_str("crowdstrike.event.ContextTimeStamp").map(String::from) {
            let date_str = date_str.as_str();
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("event.created", dt.to_rfc3339())?;
                    }
                }
            }
        }

            if event.has("crowdstrike.event.MobileDetectionId") {
                event.rename("crowdstrike.event.MobileDetectionId", "event.id")?;
            }

        if event.has("event.id") {
            if let Some(val) = event.get("event.id") {
                let converted = match val {
                    Value::String(_) => val.clone(),
                    Value::Number(n) => json!(n.to_string()),
                    Value::Bool(b) => json!(b.to_string()),
                    Value::Null => json!("null"),
                    _ => json!(val.to_string()),
                };
                event.set("event.id", converted)?;
            }
        }

            if event.has("crowdstrike.event.DetectId") {
                event.rename("crowdstrike.event.DetectId", "rule.id")?;
            }

            if event.has("crowdstrike.event.DetectName") {
                event.rename("crowdstrike.event.DetectName", "rule.name")?;
            }

            if event.has("crowdstrike.event.DetectDescription") {
                event.rename("crowdstrike.event.DetectDescription", "rule.description")?;
            }

        event.set("threat.framework", json!("MITRE ATT&CK"))?;

        // TODO: conditional: ctx.crowdstrike?.event?.Technique != null
        {
            event.append("threat.technique.name", event.get("crowdstrike.event.Technique").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.TechniqueId != null
        {
            event.append("threat.technique.id", event.get("crowdstrike.event.TechniqueId").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.Tactic != null
        {
            event.append("threat.tactic.name", event.get("crowdstrike.event.Tactic").cloned().unwrap_or(Value::Null))?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.TacticId != null
        {
            event.append("threat.tactic.id", event.get("crowdstrike.event.TacticId").cloned().unwrap_or(Value::Null))?;
        }

            if event.has("crowdstrike.event.ComputerName") {
                event.rename("crowdstrike.event.ComputerName", "host.name")?;
            }

            if event.has("crowdstrike.event.UserName") {
                event.rename("crowdstrike.event.UserName", "user.name")?;
            }

            if event.has("crowdstrike.event.FalconHostLink") {
                event.rename("crowdstrike.event.FalconHostLink", "event.reference")?;
            }

            if event.has("crowdstrike.event.Severity") {
                event.rename("crowdstrike.event.Severity", "event.severity")?;
            }

            if event.has("crowdstrike.event.SensorId") {
                event.rename("crowdstrike.event.SensorId", "device.id")?;
            }

            if event.has("crowdstrike.event.ProcessId") {
                event.rename("crowdstrike.event.ProcessId", "process.pid")?;
            }

        Ok(TransformResult::Continue)
    }
}
