// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 HYPERI PTY LIMITED
//
// Generated by dfe-codegen. Do not edit.

use dfe_runtime::prelude::*;

/// Transform for the `recon_notification_summary` pipeline.
pub struct ReconNotificationSummary;

impl Transform for ReconNotificationSummary {
    fn name(&self) -> &str {
        "recon_notification_summary"
    }

    fn transform(&self, event: &mut Event) -> Result<TransformResult> {
        event.set("event.kind", json!("event"))?;

        event.append("event.category", json!("threat"))?;

        event.append("event.type", json!("indicator"))?;

        // TODO: conditional: ctx.crowdstrike?.event?.ItemType == null
        {
            event.set("event.action", json!("recon-notification"))?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.ItemType != null
        {
            event.set(
                "event.action",
                json!(format!(
                    "recon-notification-{}",
                    event
                        .get_str("ctx.crowdstrike.event.ItemType")
                        .unwrap_or("")
                )),
            )?;
        }

        if event.has("crowdstrike.event.ItemId") {
            event.rename("crowdstrike.event.ItemId", "event.id")?;
        }

        if event.has("crowdstrike.event.RuleId") {
            event.rename("crowdstrike.event.RuleId", "rule.id")?;
        }

        if event.has("crowdstrike.event.RuleName") {
            event.rename("crowdstrike.event.RuleName", "rule.name")?;
        }

        if event.has("crowdstrike.event.RuleTopic") {
            event.rename("crowdstrike.event.RuleTopic", "rule.ruleset")?;
        }

        if event.has("crowdstrike.event.RuleTopic") {
            event.rename("crowdstrike.event.RuleTopic", "rule.description")?;
        }

        // TODO: conditional: ctx.crowdstrike?.event?.MatchedTimestamp != null && String.valueOf(ctx.crowdstrike.event.MatchedTimestamp).length() >= 12
        {
            if let Some(date_str) = event
                .get_str("crowdstrike.event.MatchedTimestamp")
                .map(String::from)
            {
                let date_str = date_str.as_str();
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("event.created", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional: ctx.crowdstrike?.event?.MatchedTimestamp != null && String.valueOf(ctx.crowdstrike.event.MatchedTimestamp).length() <= 11
        {
            if let Some(date_str) = event
                .get_str("crowdstrike.event.MatchedTimestamp")
                .map(String::from)
            {
                let date_str = date_str.as_str();
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("event.created", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional: ctx.crowdstrike?.event?.ItemPostedTimestamp != null && String.valueOf(ctx.crowdstrike.event.ItemPostedTimestamp).length() >= 12
        {
            if let Some(date_str) = event
                .get_str("crowdstrike.event.ItemPostedTimestamp")
                .map(String::from)
            {
                let date_str = date_str.as_str();
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("event.created", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional: ctx.crowdstrike?.event?.ItemPostedTimestamp != null && String.valueOf(ctx.crowdstrike.event.ItemPostedTimestamp).length() <= 11
        {
            if let Some(date_str) = event
                .get_str("crowdstrike.event.ItemPostedTimestamp")
                .map(String::from)
            {
                let date_str = date_str.as_str();
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("event.created", dt.to_rfc3339())?;
                    }
                }
            }
        }

        Ok(TransformResult::Continue)
    }
}
