// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 HYPERI PTY LIMITED
//
// Generated by dfe-codegen. Do not edit.

use dfe_runtime::prelude::*;

/// Transform for the `remote_response_session_start` pipeline.
pub struct RemoteResponseSessionStart;

impl Transform for RemoteResponseSessionStart {
    fn name(&self) -> &str {
        "remote_response_session_start"
    }

    fn transform(&self, event: &mut Event) -> Result<TransformResult> {
        event.set("event.kind", json!("event"))?;

            event.append("event.category", json!("network"))?;
            event.append("event.category", json!("session"))?;

            event.append("event.action", json!("remote_response_session_start_event"))?;

            event.append("event.type", json!("start"))?;

            if event.has("crowdstrike.event.UserName") {
                event.rename("crowdstrike.event.UserName", "user.name")?;
            }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.StartTimestamp != null && String.valueOf(ctx.crowdstrike.event.StartTimestamp).length() >= 12
        {
            if let Some(date_str) = event.get_string("crowdstrike.event.StartTimestamp") {
                // Try UNIX_MS timestamp
                if let Ok(ms) = date_str.parse::<i64>() {
                    if let Some(dt) = chrono::DateTime::from_timestamp_millis(ms) {
                        event.set("event.start", dt.to_rfc3339())?;
                    }
                }
            }
        }

        // TODO: conditional not transpiled: ctx.crowdstrike?.event?.StartTimestamp != null && String.valueOf(ctx.crowdstrike.event.StartTimestamp).length() <= 11
        {
            if let Some(date_str) = event.get_string("crowdstrike.event.StartTimestamp") {
                // Try UNIX timestamp
                if let Ok(ts) = date_str.parse::<f64>() {
                    let secs = ts as i64;
                    let nsecs = ((ts - secs as f64) * 1_000_000_000.0) as u32;
                    if let Some(dt) = chrono::DateTime::from_timestamp(secs, nsecs) {
                        event.set("event.start", dt.to_rfc3339())?;
                    }
                }
            }
        }

        event.set("message", json!("Remote response session started."))?;

            if event.has("crowdstrike.event.HostnameField") {
                event.rename("crowdstrike.event.HostnameField", "host.name")?;
            }

        Ok(TransformResult::Continue)
    }
}
