// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 HYPERI PTY LIMITED
//
// Generated by dfe-codegen. Do not edit.

use dfe_runtime::prelude::*;

/// Transform for the `user_activity_audit` pipeline.
pub struct UserActivityAudit;

impl Transform for UserActivityAudit {
    fn name(&self) -> &str {
        "user_activity_audit"
    }

    fn transform(&self, event: &mut Event) -> Result<TransformResult> {
        event.set("event.kind", json!("event"))?;

            event.append("event.category", json!("iam"))?;

            event.append("event.type", json!("change"))?;

        event.set("event.action", json!("user_activity_audit_event"))?;

            if event.has("crowdstrike.event.UserId") {
                event.rename("crowdstrike.event.UserId", "user.name")?;
            }

            if event.has("crowdstrike.event.OperationName") {
                event.rename("crowdstrike.event.OperationName", "message")?;
            }

        // TODO: conditional: ctx.crowdstrike?.event?.UserIp != null && ctx.crowdstrike?.event?.UserIp != ""
        {
            if event.has("crowdstrike.event.UserIp") {
                event.rename("crowdstrike.event.UserIp", "source.ip")?;
            }
        }

        Ok(TransformResult::Continue)
    }
}
