// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 HYPERI PTY LIMITED
//
// Generated by dfe-codegen. Do not edit.

use dfe_runtime::prelude::*;

/// Transform for the `flows` pipeline.
pub struct Flows;

impl Transform for Flows {
    fn name(&self) -> &str {
        "flows"
    }

    fn transform(&self, event: &mut Event) -> Result<TransformResult> {
        // Pattern definitions for grok
        // TYPE = flows|firewall|vpn_firewall|cellular_firewall|bridge_anyconnect_client_vpn_firewall
        if let Some(input) = event.get_string("event.original") {
            // Grok pattern: %{TYPE}( %{NOTSPACE:cisco_meraki.flows.op})? src=%{IP:source.ip:ip} dst=%{IP:destination.ip:ip}( mac=%{MAC:source.mac})? protocol=%{NOTSPACE:network.protocol}( type=%{NOTSPACE})?( sport=%{NONNEGINT:source.port:long})?( dport=%{NONNEGINT:destination.port:long})?( pattern: %{GREEDYDATA:cisco_meraki.firewall.pattern})?
            cached_grok!("%{TYPE}( %{NOTSPACE:cisco_meraki.flows.op})? src=%{IP:source.ip:ip} dst=%{IP:destination.ip:ip}( mac=%{MAC:source.mac})? protocol=%{NOTSPACE:network.protocol}( type=%{NOTSPACE})?( sport=%{NONNEGINT:source.port:long})?( dport=%{NONNEGINT:destination.port:long})?( pattern: %{GREEDYDATA:cisco_meraki.firewall.pattern})?").extract_into(&input, event)?;
        }

        // SKIPPED: condition not transpiled: ctx.cisco_meraki?.firewall?.pattern != null && (ctx.cisco_meraki.firewall.pattern.startsWith('allow') || ctx.cisco_meraki.firewall.pattern.startsWith('deny'))
        #[allow(unreachable_code, unused_variables)]
        if false {
            // ignore_failure: true
            let _ = (|| -> Result<()> {
                if let Some(input) = event.get_string("cisco_meraki.firewall.pattern") {
                    // Grok pattern: %{NOTSPACE:cisco_meraki.firewall.action} %{GREEDYDATA:cisco_meraki.firewall.rule}
                    cached_grok!("%{NOTSPACE:cisco_meraki.firewall.action} %{GREEDYDATA:cisco_meraki.firewall.rule}").extract_into(&input, event)?;
                }
                Ok(())
            })();
        }

        let _cond = { event.has("cisco_meraki.firewall.rule") };
        if _cond {
            if event.remove("cisco_meraki.firewall.pattern").is_none() {
                return Err(TransformError::FieldNotFound {
                    path: "cisco_meraki.firewall.pattern".into(),
                });
            }
        }

        if event.has("source.mac") {
            if let Some(s) = event.get_string("source.mac") {
                let re = regex::Regex::new("[:.]").unwrap();
                let replaced = re.replace_all(&s, "-").into_owned();
                event.set("source.mac", replaced)?;
            }
        }

        let _cond = { !event.has("cisco_meraki.flows.op") };
        if _cond {
            event.set("cisco_meraki.event_subtype", json!("ip_session_initiated"))?;
        }

        let _cond = { event.get_str("cisco_meraki.flows.op") == Some("allow") };
        if _cond {
            event.set("cisco_meraki.event_subtype", json!("flow_allowed"))?;
        }

        let _cond = { event.get_str("cisco_meraki.flows.op") == Some("deny") };
        if _cond {
            event.set("cisco_meraki.event_subtype", json!("flow_denied"))?;
        }

        // --- Post-processing (codegen-emitted) ---
        // Dedup related.* arrays (same value can be appended multiple times)
        if let Some(Value::Array(mut arr)) = event.get("related.ip").cloned() {
            dedup_array(&mut arr);
            event.set("related.ip", Value::Array(arr))?;
        }
        if let Some(Value::Array(mut arr)) = event.get("related.user").cloned() {
            dedup_array(&mut arr);
            event.set("related.user", Value::Array(arr))?;
        }
        if let Some(Value::Array(mut arr)) = event.get("related.hash").cloned() {
            dedup_array(&mut arr);
            event.set("related.hash", Value::Array(arr))?;
        }
        if let Some(Value::Array(mut arr)) = event.get("related.hosts").cloned() {
            dedup_array(&mut arr);
            event.set("related.hosts", Value::Array(arr))?;
        }
        // Final cleanup: remove null/empty fields created during processing
        painless_drop_empty(event.as_value_mut());

        Ok(TransformResult::Continue)
    }
}
