// SPDX-License-Identifier: FSL-1.1-ALv2
// Copyright (c) 2026 HYPERI PTY LIMITED
//
// Generated by dfe-codegen. Do not edit.

use dfe_runtime::prelude::*;

/// Transform for the `urls` pipeline.
pub struct Urls;

impl Transform for Urls {
    fn name(&self) -> &str {
        "urls"
    }

    fn transform(&self, event: &mut Event) -> Result<TransformResult> {
        if let Some(input) = event.get_str("event.original").map(String::from) {
            let input = input.as_str();
            let mut remaining = input;
            if let Some(pos) = remaining.find(" urls ") {
                remaining = &remaining[pos..];
            }
            if let Some(rest) = remaining.strip_prefix(" urls ") {
                remaining = rest;
            }
            if let Some(pos) = remaining.find("=") {
                event.set("src", &remaining[..pos])?;
                remaining = &remaining[pos..];
            }
            if let Some(rest) = remaining.strip_prefix("=") {
                remaining = rest;
            }
            if let Some(pos) = remaining.find(" ") {
                event.set("src", &remaining[..pos])?;
                remaining = &remaining[pos..];
            }
            if let Some(rest) = remaining.strip_prefix(" ") {
                remaining = rest;
            }
            if let Some(pos) = remaining.find("=") {
                event.set("dst", &remaining[..pos])?;
                remaining = &remaining[pos..];
            }
            if let Some(rest) = remaining.strip_prefix("=") {
                remaining = rest;
            }
            if let Some(pos) = remaining.find(" ") {
                event.set("dst", &remaining[..pos])?;
                remaining = &remaining[pos..];
            }
            if let Some(rest) = remaining.strip_prefix(" ") {
                remaining = rest;
            }
            if let Some(pos) = remaining.find("=") {
                event.set("mac", &remaining[..pos])?;
                remaining = &remaining[pos..];
            }
            if let Some(rest) = remaining.strip_prefix("=") {
                remaining = rest;
            }
            if let Some(pos) = remaining.find(" request: ") {
                event.set("mac", &remaining[..pos])?;
                remaining = &remaining[pos..];
            }
            if let Some(rest) = remaining.strip_prefix(" request: ") {
                remaining = rest;
            }
            if let Some(pos) = remaining.find(" ") {
                event.set("http.request.method", &remaining[..pos])?;
                remaining = &remaining[pos..];
            }
            if let Some(rest) = remaining.strip_prefix(" ") {
                remaining = rest;
            }
            event.set("url.original", remaining)?;
        }

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if event.has("mac") {
                if let Some(input) = event.get_str("mac").map(String::from) {
                    let input = input.as_str();
                    let mut remaining = input;
                    if let Some(pos) = remaining.find(" agent=") {
                        event.set("mac", &remaining[..pos])?;
                        remaining = &remaining[pos..];
                    }
                    if let Some(rest) = remaining.strip_prefix(" agent=") {
                        remaining = rest;
                    }
                    event.set("user_agent.original", remaining)?;
                }
            }
            Ok(())
        })();

        // Pattern definitions for grok
        // IPV6NOCOMPRESS = ([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}
        // PORT = [0-9]+
        // IPV6PORTSEP = (?: port |[p#.])
        if let Some(input) = event.get_str("src").map(String::from) {
            let input = input.as_str();
            // Grok pattern: ^%{IPV4:_temp.src_ip}:%{PORT:sport}$
            // TODO: Replace with dfe-parse Layer 1/2/3 calls after grok analyser (2.1.2)
            let grok_re =
                regex::Regex::new(&grok_to_regex("^%{IPV4:_temp.src_ip}:%{PORT:sport}$")).unwrap();
            if let Some(caps) = grok_re.captures(input) {
                for name in grok_re.capture_names().flatten() {
                    if let Some(m) = caps.name(name) {
                        event.set(name, m.as_str())?;
                    }
                }
            }
            // Additional grok pattern 1: ^\\[%{IPV6:_temp.src_ip}\\]:%{PORT:sport}$
            // Additional grok pattern 2: ^%{IPV6NOCOMPRESS:_temp.src_ip}:%{PORT:sport}$
            // Additional grok pattern 3: ^%{IPV6:_temp.src_ip}%{IPV6PORTSEP}%{PORT:sport}$
        }

        if let Some(s) = event.get_str("_temp.src_ip").map(String::from) {
            let s = s.as_str();
            // Validate IP format
            let s = s.trim();
            if s.parse::<std::net::IpAddr>().is_err() {
                return Err(TransformError::ParseError {
                    path: "_temp.src_ip".into(),
                    message: format!("cannot convert '{}' to IP", s),
                }
                .into());
            }
            event.set("source.ip", s)?;
        }

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if let Some(val) = event.get("sport") {
                let converted = match val {
                    Value::String(s) => {
                        let s = s.trim();
                        if let Some(hex) = s.strip_prefix("0x") {
                            json!(i64::from_str_radix(hex, 16).map_err(|_| {
                                TransformError::ParseError {
                                    path: "sport".into(),
                                    message: format!("cannot convert '{}' to integer", s),
                                }
                            })?)
                        } else {
                            json!(s.parse::<i64>().map_err(|_| TransformError::ParseError {
                                path: "sport".into(),
                                message: format!("cannot convert '{}' to integer", s)
                            })?)
                        }
                    }
                    Value::Number(n) => {
                        json!(n.as_i64().unwrap_or(n.as_f64().unwrap_or(0.0) as i64))
                    }
                    Value::Bool(b) => json!(if *b { 1 } else { 0 }),
                    _ => {
                        return Err(TransformError::ParseError {
                            path: "sport".into(),
                            message: "cannot convert to integer".into(),
                        }
                        .into());
                    }
                };
                event.set("source.port", converted)?;
            }
            Ok(())
        })();

        // Pattern definitions for grok
        // IPV6PORTSEP = (?: port |[p#.])
        // PORT = [0-9]+
        // IPV6NOCOMPRESS = ([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}
        if let Some(input) = event.get_str("dst").map(String::from) {
            let input = input.as_str();
            // Grok pattern: ^%{IPV4:_temp.dst_ip}:%{PORT:dport}$
            // TODO: Replace with dfe-parse Layer 1/2/3 calls after grok analyser (2.1.2)
            let grok_re =
                regex::Regex::new(&grok_to_regex("^%{IPV4:_temp.dst_ip}:%{PORT:dport}$")).unwrap();
            if let Some(caps) = grok_re.captures(input) {
                for name in grok_re.capture_names().flatten() {
                    if let Some(m) = caps.name(name) {
                        event.set(name, m.as_str())?;
                    }
                }
            }
            // Additional grok pattern 1: ^\\[%{IPV6:_temp.dst_ip}\\]:%{PORT:dport}$
            // Additional grok pattern 2: ^%{IPV6NOCOMPRESS:_temp.dst_ip}:%{PORT:dport}$
            // Additional grok pattern 3: ^%{IPV6:_temp.dst_ip}%{IPV6PORTSEP}%{PORT:dport}$
        }

        // ignore_failure: true
        let _ = (|| -> Result<()> {
            if let Some(s) = event.get_str("_temp.dst_ip").map(String::from) {
                let s = s.as_str();
                // Validate IP format
                let s = s.trim();
                if s.parse::<std::net::IpAddr>().is_err() {
                    return Err(TransformError::ParseError {
                        path: "_temp.dst_ip".into(),
                        message: format!("cannot convert '{}' to IP", s),
                    }
                    .into());
                }
                event.set("destination.ip", s)?;
            }
            Ok(())
        })();

        // TODO: conditional: ctx?.dport != "0" && ctx?.cisco_meraki?.event_subtype != 'security_filtering_disposition_change'
        {
            // ignore_failure: true
            let _ = (|| -> Result<()> {
                if let Some(val) = event.get("dport") {
                    let converted = match val {
                        Value::String(s) => {
                            let s = s.trim();
                            if let Some(hex) = s.strip_prefix("0x") {
                                json!(i64::from_str_radix(hex, 16).map_err(|_| {
                                    TransformError::ParseError {
                                        path: "dport".into(),
                                        message: format!("cannot convert '{}' to integer", s),
                                    }
                                })?)
                            } else {
                                json!(s.parse::<i64>().map_err(|_| TransformError::ParseError {
                                    path: "dport".into(),
                                    message: format!("cannot convert '{}' to integer", s)
                                })?)
                            }
                        }
                        Value::Number(n) => {
                            json!(n.as_i64().unwrap_or(n.as_f64().unwrap_or(0.0) as i64))
                        }
                        Value::Bool(b) => json!(if *b { 1 } else { 0 }),
                        _ => {
                            return Err(TransformError::ParseError {
                                path: "dport".into(),
                                message: "cannot convert to integer".into(),
                            }
                            .into());
                        }
                    };
                    event.set("destination.port", converted)?;
                }
                Ok(())
            })();
        }

        if let Some(s) = event.get_str("mac").map(String::from) {
            let s = s.as_str();
            let re = regex::Regex::new("[-:.]").unwrap();
            let replaced = re.replace_all(s, "-").into_owned();
            event.set("cisco_meraki.urls.mac", replaced)?;
        }

        // TODO: conditional: ctx?.http?.request?.method.toLowerCase() != 'unknown'
        {
            event.set("cisco_meraki.event_subtype", json!("http_access"))?;
        }

        // TODO: conditional: ctx?.http?.request?.method.toLowerCase() == 'unknown'
        {
            event.set("cisco_meraki.event_subtype", json!("http_access_error"))?;
        }

        if event.has("user_agent.original") {
            if let Some(ua_str) = event.get_str("user_agent.original").map(String::from) {
                let ua_str = ua_str.as_str();
                let ua_str = ua_str.to_string();
                // User agent parsing
                if let Ok(ua) = parse_user_agent(&ua_str) {
                    event.set("user_agent.original", json!(ua_str))?;
                    if let Some(name) = ua.name {
                        event.set("user_agent.name", json!(name))?;
                    }
                    if let Some(version) = ua.version {
                        event.set("user_agent.version", json!(version))?;
                    }
                    if let Some(os_name) = ua.os_name {
                        event.set("user_agent.os.name", json!(os_name))?;
                        if let Some(os_version) = ua.os_version {
                            event.set("user_agent.os.version", json!(os_version))?;
                            event.set(
                                "user_agent.os.full",
                                json!(format!("{} {}", os_name, os_version)),
                            )?;
                        }
                    }
                    if let Some(device) = ua.device {
                        event.set("user_agent.device.name", json!(device))?;
                    }
                }
            }
        }

        // TODO: conditional: ctx.url?.original != null && ctx.url.original != ""
        {
            if let Some(uri_str) = event.get_str("url.original").map(String::from) {
                let uri_str = uri_str.as_str();
                if let Ok(url) = url::Url::parse(uri_str) {
                    event.set("url.scheme", url.scheme())?;
                    if let Some(host) = url.host_str() {
                        event.set("url.domain", host)?;
                    }
                    if let Some(port) = url.port() {
                        event.set("url.port", json!(port))?;
                    }
                    event.set("url.path", url.path())?;
                    if let Some(query) = url.query() {
                        event.set("url.query", query)?;
                    }
                    if let Some(fragment) = url.fragment() {
                        event.set("url.fragment", fragment)?;
                    }
                    if let Some(userinfo) = url.password() {
                        event.set("url.user_info", format!("{}:{}", url.username(), userinfo))?;
                    } else if !url.username().is_empty() {
                        event.set("url.user_info", url.username())?;
                    }
                }
            }
        }

        if event.has("url.domain") {
            if let Some(domain_str) = event.get_str("url.domain").map(String::from) {
                let domain_str = domain_str.as_str();
                let domain = domain_str.to_string();
                event.set("url.domain", json!(domain.clone()))?;
                // Public suffix list lookup for registered domain extraction
                if let Some(rd) = registered_domain_lookup(&domain) {
                    event.set("url.registered_domain", json!(rd.registered_domain))?;
                    event.set("url.top_level_domain", json!(rd.top_level_domain))?;
                    if let Some(sub) = rd.subdomain {
                        event.set("url.subdomain", json!(sub))?;
                    }
                }
            }
        }

        Ok(TransformResult::Continue)
    }
}
