// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 HYPERI PTY LIMITED

//! Source name to transform lookup.
//!
//! The name is the module path with dots, e.g. `filebeat.okta.default`.
//! Resolution happens once at startup, not per event.

use dfe_runtime::Transform;
use dfe_transforms::filebeat;

use crate::envelope::Envelope;

/// What a syslog-origin pipeline expects to find in `message`.
///
/// The two families disagree, and getting it wrong is silent: a header handed
/// to a body-only pipeline corrupts its first field, and a body handed to a
/// line pipeline fails its first grok.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Framing {
    /// The whole syslog line, header included -- the pipeline groks it out.
    /// `fortinet` wants `<PRI>`; `cisco_ios` and `cisco_nexus` want more.
    Line,
    /// The MSG body alone. `panw` reads it as CSV and `cisco_meraki` as
    /// key-value, so a prefixed header would corrupt the first field.
    Body,
}

/// Every way a source's payload can reach this service.
///
/// The transform is the same whichever it is -- only the wrapper differs, and
/// `envelope` unwraps it -- so this says which wrappers are ACTUALLY available
/// for a given source rather than assuming Elastic's.
///
/// `Beats` is always available: every source here has an Elastic integration.
/// `Receiver` is available when a device pushes the data, which the
/// integration declares by shipping tcp/udp agent streams. `Fetcher` is
/// available when Elastic's agent input is a pure transport -- `httpjson`,
/// `cel`, `aws-s3`, `azure-eventhub`, `streaming` -- because then the ingest
/// pipeline does all the parsing and dfe-fetcher can obtain the same bytes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Intake {
    /// The wrappers this source accepts, `Beats` always among them.
    pub envelopes: &'static [Envelope],
    /// What a syslog delivery must leave in `message`. `None` unless the
    /// source accepts [`Envelope::Receiver`].
    pub framing: Option<Framing>,
}

impl Intake {
    /// Whether `envelope` is a way this source can be delivered.
    #[must_use]
    pub fn accepts(&self, envelope: Envelope) -> bool {
        self.envelopes.contains(&envelope)
    }
}

/// Beats and nothing else.
///
/// The agent input is neither a pure transport nor something a device pushes:
/// an ETW trace or a Windows event log is read off the host by the agent, and
/// there is no other way to the same bytes.
const fn agent_only() -> Intake {
    Intake {
        envelopes: &[Envelope::Beats],
        framing: None,
    }
}

/// Beats plus a device pushing into dfe-receiver.
const fn pushed(framing: Framing) -> Intake {
    Intake {
        envelopes: &[Envelope::Beats, Envelope::Receiver],
        framing: Some(framing),
    }
}

/// Beats plus us fetching the same bytes the agent would.
const fn fetched() -> Intake {
    Intake {
        envelopes: &[Envelope::Beats, Envelope::Fetcher],
        framing: None,
    }
}

/// Every transform this service can run, keyed by source name.
///
/// Sorted so the `sources()` listing is stable. The entries are hand-wired
/// because each names a Rust type, and `sources.yaml` is asserted against them
/// so a source declared there and never wired here fails the build.
///
/// The fourth element is the data stream this source's events belong to,
/// `<package>.<data_stream>`. Not derivable from the source name -- fortinet's
/// package is `fortinet_fortigate` and one azure package is four of our
/// modules -- so it is declared alongside the rest.
static TRANSFORMS: &[(&str, &(dyn Transform + Sync), Intake, &str)] = &[
    (
        "filebeat.1password_audit_events.default",
        &filebeat::_1password_audit_events::default::Default,
        fetched(),
        "1password.audit_events",
    ),
    (
        "filebeat.1password_item_usages.default",
        &filebeat::_1password_item_usages::default::Default,
        fetched(),
        "1password.item_usages",
    ),
    (
        "filebeat.1password_signin_attempts.default",
        &filebeat::_1password_signin_attempts::default::Default,
        fetched(),
        "1password.signin_attempts",
    ),
    (
        "filebeat.abnormal_security_ai_security_mailbox.default",
        &filebeat::abnormal_security_ai_security_mailbox::default::Default,
        fetched(),
        "abnormal_security.ai_security_mailbox",
    ),
    (
        "filebeat.abnormal_security_ai_security_mailbox_not_analyzed.default",
        &filebeat::abnormal_security_ai_security_mailbox_not_analyzed::default::Default,
        fetched(),
        "abnormal_security.ai_security_mailbox_not_analyzed",
    ),
    (
        "filebeat.abnormal_security_audit.default",
        &filebeat::abnormal_security_audit::default::Default,
        fetched(),
        "abnormal_security.audit",
    ),
    (
        "filebeat.abnormal_security_case.default",
        &filebeat::abnormal_security_case::default::Default,
        fetched(),
        "abnormal_security.case",
    ),
    (
        "filebeat.abnormal_security_threat.default",
        &filebeat::abnormal_security_threat::default::Default,
        fetched(),
        "abnormal_security.threat",
    ),
    (
        "filebeat.abnormal_security_vendor_case.default",
        &filebeat::abnormal_security_vendor_case::default::Default,
        fetched(),
        "abnormal_security.vendor_case",
    ),
    (
        "filebeat.activemq_audit.default",
        &filebeat::activemq_audit::default::Default,
        agent_only(),
        "activemq.audit",
    ),
    (
        "filebeat.activemq_broker.default",
        &filebeat::activemq_broker::default::Default,
        agent_only(),
        "activemq.broker",
    ),
    (
        "filebeat.activemq_log.default",
        &filebeat::activemq_log::default::Default,
        agent_only(),
        "activemq.log",
    ),
    (
        "filebeat.activemq_queue.default",
        &filebeat::activemq_queue::default::Default,
        agent_only(),
        "activemq.queue",
    ),
    (
        "filebeat.activemq_topic.default",
        &filebeat::activemq_topic::default::Default,
        agent_only(),
        "activemq.topic",
    ),
    (
        "filebeat.admin_by_request_epm_auditlog.default",
        &filebeat::admin_by_request_epm_auditlog::default::Default,
        fetched(),
        "admin_by_request_epm.auditlog",
    ),
    (
        "filebeat.admin_by_request_epm_events.default",
        &filebeat::admin_by_request_epm_events::default::Default,
        fetched(),
        "admin_by_request_epm.events",
    ),
    (
        "filebeat.agentless_hello_world_generic.default",
        &filebeat::agentless_hello_world_generic::default::Default,
        fetched(),
        "agentless_hello_world.generic",
    ),
    (
        "filebeat.agentless_hello_world_mock_counter.default",
        &filebeat::agentless_hello_world_mock_counter::default::Default,
        fetched(),
        "agentless_hello_world.mock_counter",
    ),
    (
        "filebeat.amazon_security_lake_event.default",
        &filebeat::amazon_security_lake_event::default::Default,
        fetched(),
        "amazon_security_lake.event",
    ),
    (
        "filebeat.anthropic_audit.default",
        &filebeat::anthropic_audit::default::Default,
        fetched(),
        "anthropic.audit",
    ),
    (
        "filebeat.anthropic_metrics_cost.default",
        &filebeat::anthropic_metrics_cost::default::Default,
        fetched(),
        "anthropic_metrics.cost",
    ),
    (
        "filebeat.anthropic_metrics_rate_limit.default",
        &filebeat::anthropic_metrics_rate_limit::default::Default,
        fetched(),
        "anthropic_metrics.rate_limit",
    ),
    (
        "filebeat.anthropic_metrics_usage.default",
        &filebeat::anthropic_metrics_usage::default::Default,
        fetched(),
        "anthropic_metrics.usage",
    ),
    (
        "filebeat.apache_access.default",
        &filebeat::apache_access::default::Default,
        agent_only(),
        "apache.access",
    ),
    (
        "filebeat.apache_error.default",
        &filebeat::apache_error::default::Default,
        agent_only(),
        "apache.error",
    ),
    (
        "filebeat.arista_ngfw_log.default",
        &filebeat::arista_ngfw_log::default::Default,
        pushed(Framing::Line),
        "arista_ngfw.log",
    ),
    (
        "filebeat.atlassian_bitbucket_audit.default",
        &filebeat::atlassian_bitbucket_audit::default::Default,
        fetched(),
        "atlassian_bitbucket.audit",
    ),
    (
        "filebeat.atlassian_cloud_audit.default",
        &filebeat::atlassian_cloud_audit::default::Default,
        fetched(),
        "atlassian_cloud.audit",
    ),
    (
        "filebeat.atlassian_confluence_audit.default",
        &filebeat::atlassian_confluence_audit::default::Default,
        fetched(),
        "atlassian_confluence.audit",
    ),
    (
        "filebeat.auditd_manager_auditd.default",
        &filebeat::auditd_manager_auditd::default::Default,
        agent_only(),
        "auditd_manager.auditd",
    ),
    (
        "filebeat.auth0_logs.default",
        &filebeat::auth0_logs::default::Default,
        pushed(Framing::Body),
        "auth0.logs",
    ),
    (
        "filebeat.aws_apigateway_logs.default",
        &filebeat::aws_apigateway_logs::default::Default,
        fetched(),
        "aws.apigateway_logs",
    ),
    (
        "filebeat.aws_awshealth.default",
        &filebeat::aws_awshealth::default::Default,
        fetched(),
        "aws.awshealth",
    ),
    (
        "filebeat.aws_billing.default",
        &filebeat::aws_billing::default::Default,
        fetched(),
        "aws.billing",
    ),
    (
        "filebeat.aws_cloudfront_logs.default",
        &filebeat::aws_cloudfront_logs::default::Default,
        fetched(),
        "aws.cloudfront_logs",
    ),
    (
        "filebeat.aws_cloudtrail.default",
        &filebeat::aws_cloudtrail::default::Default,
        fetched(),
        "aws.cloudtrail",
    ),
    (
        "filebeat.aws_cloudwatch_logs.default",
        &filebeat::aws_cloudwatch_logs::default::Default,
        fetched(),
        "aws.cloudwatch_logs",
    ),
    (
        "filebeat.aws_cloudwatch_metrics.default",
        &filebeat::aws_cloudwatch_metrics::default::Default,
        fetched(),
        "aws.cloudwatch_metrics",
    ),
    (
        "filebeat.aws_config.default",
        &filebeat::aws_config::default::Default,
        fetched(),
        "aws.config",
    ),
    (
        "filebeat.aws_dynamodb.default",
        &filebeat::aws_dynamodb::default::Default,
        fetched(),
        "aws.dynamodb",
    ),
    (
        "filebeat.aws_ec2_logs.default",
        &filebeat::aws_ec2_logs::default::Default,
        fetched(),
        "aws.ec2_logs",
    ),
    (
        "filebeat.aws_ec2_metrics.default",
        &filebeat::aws_ec2_metrics::default::Default,
        fetched(),
        "aws.ec2_metrics",
    ),
    (
        "filebeat.aws_elb_logs.default",
        &filebeat::aws_elb_logs::default::Default,
        fetched(),
        "aws.elb_logs",
    ),
    (
        "filebeat.aws_emr_logs.default",
        &filebeat::aws_emr_logs::default::Default,
        fetched(),
        "aws.emr_logs",
    ),
    (
        "filebeat.aws_firewall_logs.default",
        &filebeat::aws_firewall_logs::default::Default,
        fetched(),
        "aws.firewall_logs",
    ),
    (
        "filebeat.aws_guardduty.default",
        &filebeat::aws_guardduty::default::Default,
        fetched(),
        "aws.guardduty",
    ),
    (
        "filebeat.aws_inspector.default",
        &filebeat::aws_inspector::default::Default,
        fetched(),
        "aws.inspector",
    ),
    (
        "filebeat.aws_kafka_metrics.default",
        &filebeat::aws_kafka_metrics::default::Default,
        fetched(),
        "aws.kafka_metrics",
    ),
    (
        "filebeat.aws_kinesis.default",
        &filebeat::aws_kinesis::default::Default,
        fetched(),
        "aws.kinesis",
    ),
    (
        "filebeat.aws_lambda.default",
        &filebeat::aws_lambda::default::Default,
        fetched(),
        "aws.lambda",
    ),
    (
        "filebeat.aws_lambda_logs.default",
        &filebeat::aws_lambda_logs::default::Default,
        fetched(),
        "aws.lambda_logs",
    ),
    (
        "filebeat.aws_mq_activemq_audit_logs.default",
        &filebeat::aws_mq_activemq_audit_logs::default::Default,
        fetched(),
        "aws_mq.activemq_audit_logs",
    ),
    (
        "filebeat.aws_mq_activemq_general_logs.default",
        &filebeat::aws_mq_activemq_general_logs::default::Default,
        fetched(),
        "aws_mq.activemq_general_logs",
    ),
    (
        "filebeat.aws_mq_activemq_metrics.default",
        &filebeat::aws_mq_activemq_metrics::default::Default,
        fetched(),
        "aws_mq.activemq_metrics",
    ),
    (
        "filebeat.aws_mq_rabbitmq_general_logs.default",
        &filebeat::aws_mq_rabbitmq_general_logs::default::Default,
        fetched(),
        "aws_mq.rabbitmq_general_logs",
    ),
    (
        "filebeat.aws_mq_rabbitmq_metrics.default",
        &filebeat::aws_mq_rabbitmq_metrics::default::Default,
        fetched(),
        "aws_mq.rabbitmq_metrics",
    ),
    (
        "filebeat.aws_natgateway.default",
        &filebeat::aws_natgateway::default::Default,
        fetched(),
        "aws.natgateway",
    ),
    (
        "filebeat.aws_rds.default",
        &filebeat::aws_rds::default::Default,
        fetched(),
        "aws.rds",
    ),
    (
        "filebeat.aws_redshift.default",
        &filebeat::aws_redshift::default::Default,
        fetched(),
        "aws.redshift",
    ),
    (
        "filebeat.aws_route53_public_logs.default",
        &filebeat::aws_route53_public_logs::default::Default,
        fetched(),
        "aws.route53_public_logs",
    ),
    (
        "filebeat.aws_route53_resolver_logs.default",
        &filebeat::aws_route53_resolver_logs::default::Default,
        fetched(),
        "aws.route53_resolver_logs",
    ),
    (
        "filebeat.aws_s3_daily_storage.default",
        &filebeat::aws_s3_daily_storage::default::Default,
        fetched(),
        "aws.s3_daily_storage",
    ),
    (
        "filebeat.aws_s3_request.default",
        &filebeat::aws_s3_request::default::Default,
        fetched(),
        "aws.s3_request",
    ),
    (
        "filebeat.aws_s3access.default",
        &filebeat::aws_s3access::default::Default,
        fetched(),
        "aws.s3access",
    ),
    (
        "filebeat.aws_securityhub_finding.default",
        &filebeat::aws_securityhub_finding::default::Default,
        fetched(),
        "aws_securityhub.finding",
    ),
    (
        "filebeat.aws_securityhub_findings.default",
        &filebeat::aws_securityhub_findings::default::Default,
        fetched(),
        "aws.securityhub_findings",
    ),
    (
        "filebeat.aws_securityhub_findings_full_posture.default",
        &filebeat::aws_securityhub_findings_full_posture::default::Default,
        fetched(),
        "aws.securityhub_findings_full_posture",
    ),
    (
        "filebeat.aws_securityhub_insights.default",
        &filebeat::aws_securityhub_insights::default::Default,
        fetched(),
        "aws.securityhub_insights",
    ),
    (
        "filebeat.aws_sqs.default",
        &filebeat::aws_sqs::default::Default,
        fetched(),
        "aws.sqs",
    ),
    (
        "filebeat.aws_transitgateway.default",
        &filebeat::aws_transitgateway::default::Default,
        fetched(),
        "aws.transitgateway",
    ),
    (
        "filebeat.aws_usage.default",
        &filebeat::aws_usage::default::Default,
        fetched(),
        "aws.usage",
    ),
    (
        "filebeat.aws_vpcflow.default",
        &filebeat::aws_vpcflow::default::Default,
        fetched(),
        "aws.vpcflow",
    ),
    (
        "filebeat.aws_vpn.default",
        &filebeat::aws_vpn::default::Default,
        fetched(),
        "aws.vpn",
    ),
    (
        "filebeat.aws_waf.default",
        &filebeat::aws_waf::default::Default,
        fetched(),
        "aws.waf",
    ),
    (
        "filebeat.awsfirehose_logs.default",
        &filebeat::awsfirehose_logs::default::Default,
        agent_only(),
        "awsfirehose.logs",
    ),
    (
        "filebeat.awsfirehose_metrics.default",
        &filebeat::awsfirehose_metrics::default::Default,
        agent_only(),
        "awsfirehose.metrics",
    ),
    (
        "filebeat.azure_activitylogs.default",
        &filebeat::azure_activitylogs::default::Default,
        fetched(),
        "azure.activitylogs",
    ),
    (
        "filebeat.azure_application_gateway.default",
        &filebeat::azure_application_gateway::default::Default,
        fetched(),
        "azure.application_gateway",
    ),
    (
        "filebeat.azure_auditlogs.default",
        &filebeat::azure_auditlogs::default::Default,
        fetched(),
        "azure.auditlogs",
    ),
    (
        "filebeat.azure_eventhub.default",
        &filebeat::azure_eventhub::default::Default,
        fetched(),
        "azure.eventhub",
    ),
    (
        "filebeat.azure_events.default",
        &filebeat::azure_events::default::Default,
        fetched(),
        "azure.events",
    ),
    (
        "filebeat.azure_firewall_logs.default",
        &filebeat::azure_firewall_logs::default::Default,
        fetched(),
        "azure.firewall_logs",
    ),
    (
        "filebeat.azure_functions_functionapplogs.default",
        &filebeat::azure_functions_functionapplogs::default::Default,
        fetched(),
        "azure_functions.functionapplogs",
    ),
    (
        "filebeat.azure_functions_metrics.default",
        &filebeat::azure_functions_metrics::default::Default,
        fetched(),
        "azure_functions.metrics",
    ),
    (
        "filebeat.azure_graphactivitylogs.default",
        &filebeat::azure_graphactivitylogs::default::Default,
        fetched(),
        "azure.graphactivitylogs",
    ),
    (
        "filebeat.azure_identity_protection.default",
        &filebeat::azure_identity_protection::default::Default,
        fetched(),
        "azure.identity_protection",
    ),
    (
        "filebeat.azure_metrics_compute_vm.default",
        &filebeat::azure_metrics_compute_vm::default::Default,
        fetched(),
        "azure_metrics.compute_vm",
    ),
    (
        "filebeat.azure_metrics_compute_vm_scaleset.default",
        &filebeat::azure_metrics_compute_vm_scaleset::default::Default,
        fetched(),
        "azure_metrics.compute_vm_scaleset",
    ),
    (
        "filebeat.azure_metrics_container_instance.default",
        &filebeat::azure_metrics_container_instance::default::Default,
        fetched(),
        "azure_metrics.container_instance",
    ),
    (
        "filebeat.azure_metrics_container_registry.default",
        &filebeat::azure_metrics_container_registry::default::Default,
        fetched(),
        "azure_metrics.container_registry",
    ),
    (
        "filebeat.azure_metrics_container_service.default",
        &filebeat::azure_metrics_container_service::default::Default,
        fetched(),
        "azure_metrics.container_service",
    ),
    (
        "filebeat.azure_metrics_database_account.default",
        &filebeat::azure_metrics_database_account::default::Default,
        fetched(),
        "azure_metrics.database_account",
    ),
    (
        "filebeat.azure_metrics_monitor.default",
        &filebeat::azure_metrics_monitor::default::Default,
        fetched(),
        "azure_metrics.monitor",
    ),
    (
        "filebeat.azure_metrics_storage_account.default",
        &filebeat::azure_metrics_storage_account::default::Default,
        fetched(),
        "azure_metrics.storage_account",
    ),
    (
        "filebeat.azure_network_watcher_nsg_log.default",
        &filebeat::azure_network_watcher_nsg_log::default::Default,
        fetched(),
        "azure_network_watcher_nsg.log",
    ),
    (
        "filebeat.azure_network_watcher_vnet_log.default",
        &filebeat::azure_network_watcher_vnet_log::default::Default,
        fetched(),
        "azure_network_watcher_vnet.log",
    ),
    (
        "filebeat.azure_platformlogs.default",
        &filebeat::azure_platformlogs::default::Default,
        fetched(),
        "azure.platformlogs",
    ),
    (
        "filebeat.azure_provisioning.default",
        &filebeat::azure_provisioning::default::Default,
        fetched(),
        "azure.provisioning",
    ),
    (
        "filebeat.azure_signinlogs.default",
        &filebeat::azure_signinlogs::default::Default,
        fetched(),
        "azure.signinlogs",
    ),
    (
        "filebeat.azure_springcloudlogs.default",
        &filebeat::azure_springcloudlogs::default::Default,
        fetched(),
        "azure.springcloudlogs",
    ),
    (
        "filebeat.backstage_logs.default",
        &filebeat::backstage_logs::default::Default,
        agent_only(),
        "backstage.logs",
    ),
    (
        "filebeat.barracuda_cloudgen_firewall_log.default",
        &filebeat::barracuda_cloudgen_firewall_log::default::Default,
        agent_only(),
        "barracuda_cloudgen_firewall.log",
    ),
    (
        "filebeat.bbot_asm_intel.default",
        &filebeat::bbot_asm_intel::default::Default,
        pushed(Framing::Body),
        "bbot.asm_intel",
    ),
    (
        "filebeat.beelzebub_logs.default",
        &filebeat::beelzebub_logs::default::Default,
        pushed(Framing::Body),
        "beelzebub.logs",
    ),
    (
        "filebeat.beyondtrust_isi_incident.default",
        &filebeat::beyondtrust_isi_incident::default::Default,
        pushed(Framing::Body),
        "beyondtrust_isi.incident",
    ),
    (
        "filebeat.beyondtrust_pra_access_session.default",
        &filebeat::beyondtrust_pra_access_session::default::Default,
        fetched(),
        "beyondtrust_pra.access_session",
    ),
    (
        "filebeat.bitsight_vulnerability.default",
        &filebeat::bitsight_vulnerability::default::Default,
        fetched(),
        "bitsight.vulnerability",
    ),
    (
        "filebeat.blacklens_alerts.default",
        &filebeat::blacklens_alerts::default::Default,
        fetched(),
        "blacklens.alerts",
    ),
    (
        "filebeat.carbon_black_cloud_alert_v7.default",
        &filebeat::carbon_black_cloud_alert_v7::default::Default,
        fetched(),
        "carbon_black_cloud.alert_v7",
    ),
    (
        "filebeat.carbon_black_cloud_asset_vulnerability_summary.default",
        &filebeat::carbon_black_cloud_asset_vulnerability_summary::default::Default,
        fetched(),
        "carbon_black_cloud.asset_vulnerability_summary",
    ),
    (
        "filebeat.carbon_black_cloud_audit.default",
        &filebeat::carbon_black_cloud_audit::default::Default,
        fetched(),
        "carbon_black_cloud.audit",
    ),
    (
        "filebeat.carbon_black_cloud_endpoint_event.default",
        &filebeat::carbon_black_cloud_endpoint_event::default::Default,
        fetched(),
        "carbon_black_cloud.endpoint_event",
    ),
    (
        "filebeat.carbon_black_cloud_watchlist_hit.default",
        &filebeat::carbon_black_cloud_watchlist_hit::default::Default,
        fetched(),
        "carbon_black_cloud.watchlist_hit",
    ),
    (
        "filebeat.cassandra_log.default",
        &filebeat::cassandra_log::default::Default,
        agent_only(),
        "cassandra.log",
    ),
    (
        "filebeat.cassandra_metrics.default",
        &filebeat::cassandra_metrics::default::Default,
        agent_only(),
        "cassandra.metrics",
    ),
    (
        "filebeat.cef_log.default",
        &filebeat::cef_log::default::Default,
        pushed(Framing::Line),
        "cef.log",
    ),
    (
        "filebeat.checkpoint.default",
        &filebeat::checkpoint::default::Default,
        pushed(Framing::Line),
        "checkpoint.firewall",
    ),
    (
        "filebeat.checkpoint_email_event.default",
        &filebeat::checkpoint_email_event::default::Default,
        fetched(),
        "checkpoint_email.event",
    ),
    (
        "filebeat.cisa_kevs_vulnerability.default",
        &filebeat::cisa_kevs_vulnerability::default::Default,
        fetched(),
        "cisa_kevs.vulnerability",
    ),
    (
        "filebeat.cisco_aironet_log.default",
        &filebeat::cisco_aironet_log::default::Default,
        pushed(Framing::Line),
        "cisco_aironet.log",
    ),
    (
        "filebeat.cisco_asa.default",
        &filebeat::cisco_asa::default::Default,
        pushed(Framing::Line),
        "cisco_asa.log",
    ),
    (
        "filebeat.cisco_duo_activity.default",
        &filebeat::cisco_duo_activity::default::Default,
        fetched(),
        "cisco_duo.activity",
    ),
    (
        "filebeat.cisco_duo_admin.default",
        &filebeat::cisco_duo_admin::default::Default,
        fetched(),
        "cisco_duo.admin",
    ),
    (
        "filebeat.cisco_duo_auth.default",
        &filebeat::cisco_duo_auth::default::Default,
        fetched(),
        "cisco_duo.auth",
    ),
    (
        "filebeat.cisco_duo_offline_enrollment.default",
        &filebeat::cisco_duo_offline_enrollment::default::Default,
        fetched(),
        "cisco_duo.offline_enrollment",
    ),
    (
        "filebeat.cisco_duo_summary.default",
        &filebeat::cisco_duo_summary::default::Default,
        fetched(),
        "cisco_duo.summary",
    ),
    (
        "filebeat.cisco_duo_telephony.default",
        &filebeat::cisco_duo_telephony::default::Default,
        fetched(),
        "cisco_duo.telephony",
    ),
    (
        "filebeat.cisco_duo_telephony_v2.default",
        &filebeat::cisco_duo_telephony_v2::default::Default,
        fetched(),
        "cisco_duo.telephony_v2",
    ),
    (
        "filebeat.cisco_duo_trust_monitor.default",
        &filebeat::cisco_duo_trust_monitor::default::Default,
        fetched(),
        "cisco_duo.trust_monitor",
    ),
    (
        "filebeat.cisco_ftd.default",
        &filebeat::cisco_ftd::default::Default,
        pushed(Framing::Line),
        "cisco_ftd.log",
    ),
    (
        "filebeat.cisco_ios.default",
        &filebeat::cisco_ios::default::Default,
        pushed(Framing::Line),
        "cisco_ios.log",
    ),
    (
        "filebeat.cisco_meraki.default",
        &filebeat::cisco_meraki::default::Default,
        pushed(Framing::Body),
        "cisco_meraki.log",
    ),
    (
        "filebeat.cisco_meraki_events.default",
        &filebeat::cisco_meraki_events::default::Default,
        agent_only(),
        "cisco_meraki.events",
    ),
    (
        "filebeat.cisco_meraki_metrics_device_health.default",
        &filebeat::cisco_meraki_metrics_device_health::default::Default,
        agent_only(),
        "cisco_meraki_metrics.device_health",
    ),
    (
        "filebeat.cisco_nexus.default",
        &filebeat::cisco_nexus::default::Default,
        pushed(Framing::Line),
        "cisco_nexus.log",
    ),
    (
        "filebeat.cisco_secure_email_gateway_log.default",
        &filebeat::cisco_secure_email_gateway_log::default::Default,
        pushed(Framing::Line),
        "cisco_secure_email_gateway.log",
    ),
    (
        "filebeat.cisco_umbrella.default",
        &filebeat::cisco_umbrella::default::Default,
        fetched(),
        "cisco_umbrella.log",
    ),
    (
        "filebeat.citrix_waf_log.default",
        &filebeat::citrix_waf_log::default::Default,
        pushed(Framing::Line),
        "citrix_waf.log",
    ),
    (
        "filebeat.claude_cowork_events.default",
        &filebeat::claude_cowork_events::default::Default,
        agent_only(),
        "claude_cowork.events",
    ),
    (
        "filebeat.cloud_security_posture_findings.default",
        &filebeat::cloud_security_posture_findings::default::Default,
        agent_only(),
        "cloud_security_posture.findings",
    ),
    (
        "filebeat.cloud_security_posture_vulnerabilities.default",
        &filebeat::cloud_security_posture_vulnerabilities::default::Default,
        agent_only(),
        "cloud_security_posture.vulnerabilities",
    ),
    (
        "filebeat.contrast_security_attack_event.default",
        &filebeat::contrast_security_attack_event::default::Default,
        agent_only(),
        "contrast_security.attack_event",
    ),
    (
        "filebeat.contrast_security_incident.default",
        &filebeat::contrast_security_incident::default::Default,
        agent_only(),
        "contrast_security.incident",
    ),
    (
        "filebeat.contrast_security_issue.default",
        &filebeat::contrast_security_issue::default::Default,
        agent_only(),
        "contrast_security.issue",
    ),
    (
        "filebeat.coredns_log.default",
        &filebeat::coredns_log::default::Default,
        agent_only(),
        "coredns.log",
    ),
    (
        "filebeat.coredns_log.json",
        &filebeat::coredns_log::json::Json,
        agent_only(),
        "coredns.log",
    ),
    (
        "filebeat.couchdb_server.default",
        &filebeat::couchdb_server::default::Default,
        agent_only(),
        "couchdb.server",
    ),
    (
        "filebeat.crowdstrike.default",
        &filebeat::crowdstrike::default::Default,
        fetched(),
        "crowdstrike.falcon",
    ),
    (
        "filebeat.crowdstrike_alert.default",
        &filebeat::crowdstrike_alert::default::Default,
        fetched(),
        "crowdstrike.alert",
    ),
    (
        "filebeat.crowdstrike_host.default",
        &filebeat::crowdstrike_host::default::Default,
        fetched(),
        "crowdstrike.host",
    ),
    (
        "filebeat.crowdstrike_identity_protection_assessment.default",
        &filebeat::crowdstrike_identity_protection_assessment::default::Default,
        fetched(),
        "crowdstrike.identity_protection_assessment",
    ),
    (
        "filebeat.crowdstrike_identity_protection_timeline.default",
        &filebeat::crowdstrike_identity_protection_timeline::default::Default,
        fetched(),
        "crowdstrike.identity_protection_timeline",
    ),
    (
        "filebeat.crowdstrike_vulnerability.default",
        &filebeat::crowdstrike_vulnerability::default::Default,
        fetched(),
        "crowdstrike.vulnerability",
    ),
    (
        "filebeat.cursor_audit.default",
        &filebeat::cursor_audit::default::Default,
        fetched(),
        "cursor.audit",
    ),
    (
        "filebeat.cyberark_pta_events.default",
        &filebeat::cyberark_pta_events::default::Default,
        pushed(Framing::Line),
        "cyberark_pta.events",
    ),
    (
        "filebeat.cylance_protect.default",
        &filebeat::cylance_protect::default::Default,
        pushed(Framing::Body),
        "cylance.protect",
    ),
    (
        "filebeat.dataminr_pulse_alerts.default",
        &filebeat::dataminr_pulse_alerts::default::Default,
        fetched(),
        "dataminr_pulse.alerts",
    ),
    (
        "filebeat.digital_guardian_arc.default",
        &filebeat::digital_guardian_arc::default::Default,
        fetched(),
        "digital_guardian.arc",
    ),
    (
        "filebeat.ece_adminconsole.default",
        &filebeat::ece_adminconsole::default::Default,
        agent_only(),
        "ece.adminconsole",
    ),
    (
        "filebeat.elastic_agent_elastic_agent_logs.default",
        &filebeat::elastic_agent_elastic_agent_logs::default::Default,
        agent_only(),
        "elastic_agent.elastic_agent_logs",
    ),
    (
        "filebeat.elastic_agent_status_change_logs.default",
        &filebeat::elastic_agent_status_change_logs::default::Default,
        agent_only(),
        "elastic_agent.status_change_logs",
    ),
    (
        "filebeat.elastic_package_registry_metrics.default",
        &filebeat::elastic_package_registry_metrics::default::Default,
        agent_only(),
        "elastic_package_registry.metrics",
    ),
    (
        "filebeat.elastic_security_alert.default",
        &filebeat::elastic_security_alert::default::Default,
        fetched(),
        "elastic_security.alert",
    ),
    (
        "filebeat.entityanalytics_ad_entity.default",
        &filebeat::entityanalytics_ad_entity::default::Default,
        fetched(),
        "entityanalytics_ad.entity",
    ),
    (
        "filebeat.entityanalytics_ad_entity.device",
        &filebeat::entityanalytics_ad_entity::device::Device,
        fetched(),
        "entityanalytics_ad.entity",
    ),
    (
        "filebeat.entityanalytics_ad_entity.group",
        &filebeat::entityanalytics_ad_entity::group::Group,
        fetched(),
        "entityanalytics_ad.entity",
    ),
    (
        "filebeat.entityanalytics_ad_entity.user",
        &filebeat::entityanalytics_ad_entity::user::User,
        fetched(),
        "entityanalytics_ad.entity",
    ),
    (
        "filebeat.entityanalytics_entra_id.default",
        &filebeat::entityanalytics_entra_id::default::Default,
        fetched(),
        "entityanalytics_entra_id.entity",
    ),
    (
        "filebeat.entityanalytics_entra_id.device",
        &filebeat::entityanalytics_entra_id::device::Device,
        fetched(),
        "entityanalytics_entra_id.entity",
    ),
    (
        "filebeat.entityanalytics_entra_id.user",
        &filebeat::entityanalytics_entra_id::user::User,
        fetched(),
        "entityanalytics_entra_id.entity",
    ),
    (
        "filebeat.entro_audit.default",
        &filebeat::entro_audit::default::Default,
        fetched(),
        "entro.audit",
    ),
    (
        "filebeat.ess_billing_billing.default",
        &filebeat::ess_billing_billing::default::Default,
        fetched(),
        "ess_billing.billing",
    ),
    (
        "filebeat.ess_billing_credits.default",
        &filebeat::ess_billing_credits::default::Default,
        fetched(),
        "ess_billing.credits",
    ),
    (
        "filebeat.fim_event.default",
        &filebeat::fim_event::default::Default,
        agent_only(),
        "fim.event",
    ),
    (
        "filebeat.first_epss_vulnerability.default",
        &filebeat::first_epss_vulnerability::default::Default,
        fetched(),
        "first_epss.vulnerability",
    ),
    (
        "filebeat.forcepoint_web_logs.default",
        &filebeat::forcepoint_web_logs::default::Default,
        agent_only(),
        "forcepoint_web.logs",
    ),
    (
        "filebeat.forescout_event.default",
        &filebeat::forescout_event::default::Default,
        pushed(Framing::Body),
        "forescout.event",
    ),
    (
        "filebeat.forescout_host.default",
        &filebeat::forescout_host::default::Default,
        agent_only(),
        "forescout.host",
    ),
    (
        "filebeat.fortinet.default",
        &filebeat::fortinet::default::Default,
        pushed(Framing::Line),
        "fortinet_fortigate.log",
    ),
    (
        "filebeat.fortinet_forticlient_log.default",
        &filebeat::fortinet_forticlient_log::default::Default,
        pushed(Framing::Body),
        "fortinet_forticlient.log",
    ),
    (
        "filebeat.fortinet_fortiedr_log.default",
        &filebeat::fortinet_fortiedr_log::default::Default,
        pushed(Framing::Line),
        "fortinet_fortiedr.log",
    ),
    (
        "filebeat.gcp_audit.default",
        &filebeat::gcp_audit::default::Default,
        fetched(),
        "gcp.audit",
    ),
    (
        "filebeat.gcp_billing.default",
        &filebeat::gcp_billing::default::Default,
        fetched(),
        "gcp.billing",
    ),
    (
        "filebeat.gcp_cloudrun_metrics.default",
        &filebeat::gcp_cloudrun_metrics::default::Default,
        fetched(),
        "gcp.cloudrun_metrics",
    ),
    (
        "filebeat.gcp_cloudsql_mysql.default",
        &filebeat::gcp_cloudsql_mysql::default::Default,
        fetched(),
        "gcp.cloudsql_mysql",
    ),
    (
        "filebeat.gcp_cloudsql_postgresql.default",
        &filebeat::gcp_cloudsql_postgresql::default::Default,
        fetched(),
        "gcp.cloudsql_postgresql",
    ),
    (
        "filebeat.gcp_cloudsql_sqlserver.default",
        &filebeat::gcp_cloudsql_sqlserver::default::Default,
        fetched(),
        "gcp.cloudsql_sqlserver",
    ),
    (
        "filebeat.gcp_compute.default",
        &filebeat::gcp_compute::default::Default,
        fetched(),
        "gcp.compute",
    ),
    (
        "filebeat.gcp_dataproc.default",
        &filebeat::gcp_dataproc::default::Default,
        fetched(),
        "gcp.dataproc",
    ),
    (
        "filebeat.gcp_dns.default",
        &filebeat::gcp_dns::default::Default,
        fetched(),
        "gcp.dns",
    ),
    (
        "filebeat.gcp_firestore.default",
        &filebeat::gcp_firestore::default::Default,
        fetched(),
        "gcp.firestore",
    ),
    (
        "filebeat.gcp_firewall.default",
        &filebeat::gcp_firewall::default::Default,
        fetched(),
        "gcp.firewall",
    ),
    (
        "filebeat.gcp_gke.default",
        &filebeat::gcp_gke::default::Default,
        fetched(),
        "gcp.gke",
    ),
    (
        "filebeat.gcp_loadbalancing_logs.default",
        &filebeat::gcp_loadbalancing_logs::default::Default,
        fetched(),
        "gcp.loadbalancing_logs",
    ),
    (
        "filebeat.gcp_loadbalancing_metrics.default",
        &filebeat::gcp_loadbalancing_metrics::default::Default,
        fetched(),
        "gcp.loadbalancing_metrics",
    ),
    (
        "filebeat.gcp_pubsub.default",
        &filebeat::gcp_pubsub::default::Default,
        fetched(),
        "gcp.pubsub",
    ),
    (
        "filebeat.gcp_redis.default",
        &filebeat::gcp_redis::default::Default,
        fetched(),
        "gcp.redis",
    ),
    (
        "filebeat.gcp_storage.default",
        &filebeat::gcp_storage::default::Default,
        fetched(),
        "gcp.storage",
    ),
    (
        "filebeat.gcp_vpcflow.default",
        &filebeat::gcp_vpcflow::default::Default,
        fetched(),
        "gcp.vpcflow",
    ),
    (
        "filebeat.github_audit.default",
        &filebeat::github_audit::default::Default,
        fetched(),
        "github.audit",
    ),
    (
        "filebeat.github_code_scanning.default",
        &filebeat::github_code_scanning::default::Default,
        fetched(),
        "github.code_scanning",
    ),
    (
        "filebeat.github_dependabot.default",
        &filebeat::github_dependabot::default::Default,
        fetched(),
        "github.dependabot",
    ),
    (
        "filebeat.github_issues.default",
        &filebeat::github_issues::default::Default,
        fetched(),
        "github.issues",
    ),
    (
        "filebeat.github_secret_scanning.default",
        &filebeat::github_secret_scanning::default::Default,
        fetched(),
        "github.secret_scanning",
    ),
    (
        "filebeat.github_security_advisories.default",
        &filebeat::github_security_advisories::default::Default,
        fetched(),
        "github.security_advisories",
    ),
    (
        "filebeat.goflow2_sflow.default",
        &filebeat::goflow2_sflow::default::Default,
        agent_only(),
        "goflow2.sflow",
    ),
    (
        "filebeat.golang_expvar.default",
        &filebeat::golang_expvar::default::Default,
        fetched(),
        "golang.expvar",
    ),
    (
        "filebeat.golang_heap.default",
        &filebeat::golang_heap::default::Default,
        fetched(),
        "golang.heap",
    ),
    (
        "filebeat.google_workspace_access_transparency.default",
        &filebeat::google_workspace_access_transparency::default::Default,
        fetched(),
        "google_workspace.access_transparency",
    ),
    (
        "filebeat.google_workspace_admin.default",
        &filebeat::google_workspace_admin::default::Default,
        fetched(),
        "google_workspace.admin",
    ),
    (
        "filebeat.google_workspace_alert.default",
        &filebeat::google_workspace_alert::default::Default,
        fetched(),
        "google_workspace.alert",
    ),
    (
        "filebeat.google_workspace_calendar.default",
        &filebeat::google_workspace_calendar::default::Default,
        fetched(),
        "google_workspace.calendar",
    ),
    (
        "filebeat.google_workspace_chat.default",
        &filebeat::google_workspace_chat::default::Default,
        fetched(),
        "google_workspace.chat",
    ),
    (
        "filebeat.google_workspace_chrome.default",
        &filebeat::google_workspace_chrome::default::Default,
        fetched(),
        "google_workspace.chrome",
    ),
    (
        "filebeat.google_workspace_context_aware_access.default",
        &filebeat::google_workspace_context_aware_access::default::Default,
        fetched(),
        "google_workspace.context_aware_access",
    ),
    (
        "filebeat.google_workspace_data_studio.default",
        &filebeat::google_workspace_data_studio::default::Default,
        fetched(),
        "google_workspace.data_studio",
    ),
    (
        "filebeat.google_workspace_device.default",
        &filebeat::google_workspace_device::default::Default,
        fetched(),
        "google_workspace.device",
    ),
    (
        "filebeat.google_workspace_drive.default",
        &filebeat::google_workspace_drive::default::Default,
        fetched(),
        "google_workspace.drive",
    ),
    (
        "filebeat.google_workspace_gcp.default",
        &filebeat::google_workspace_gcp::default::Default,
        fetched(),
        "google_workspace.gcp",
    ),
    (
        "filebeat.google_workspace_gmail.default",
        &filebeat::google_workspace_gmail::default::Default,
        fetched(),
        "google_workspace.gmail",
    ),
    (
        "filebeat.google_workspace_group_enterprise.default",
        &filebeat::google_workspace_group_enterprise::default::Default,
        fetched(),
        "google_workspace.group_enterprise",
    ),
    (
        "filebeat.google_workspace_groups.default",
        &filebeat::google_workspace_groups::default::Default,
        fetched(),
        "google_workspace.groups",
    ),
    (
        "filebeat.google_workspace_keep.default",
        &filebeat::google_workspace_keep::default::Default,
        fetched(),
        "google_workspace.keep",
    ),
    (
        "filebeat.google_workspace_login.default",
        &filebeat::google_workspace_login::default::Default,
        fetched(),
        "google_workspace.login",
    ),
    (
        "filebeat.google_workspace_meet.default",
        &filebeat::google_workspace_meet::default::Default,
        fetched(),
        "google_workspace.meet",
    ),
    (
        "filebeat.google_workspace_rules.default",
        &filebeat::google_workspace_rules::default::Default,
        fetched(),
        "google_workspace.rules",
    ),
    (
        "filebeat.google_workspace_saml.default",
        &filebeat::google_workspace_saml::default::Default,
        fetched(),
        "google_workspace.saml",
    ),
    (
        "filebeat.google_workspace_token.default",
        &filebeat::google_workspace_token::default::Default,
        fetched(),
        "google_workspace.token",
    ),
    (
        "filebeat.google_workspace_user_accounts.default",
        &filebeat::google_workspace_user_accounts::default::Default,
        fetched(),
        "google_workspace.user_accounts",
    ),
    (
        "filebeat.google_workspace_vault.default",
        &filebeat::google_workspace_vault::default::Default,
        fetched(),
        "google_workspace.vault",
    ),
    (
        "filebeat.greenhouse_audit.default",
        &filebeat::greenhouse_audit::default::Default,
        fetched(),
        "greenhouse.audit",
    ),
    (
        "filebeat.hackerone_report.default",
        &filebeat::hackerone_report::default::Default,
        fetched(),
        "hackerone.report",
    ),
    (
        "filebeat.haproxy_log.default",
        &filebeat::haproxy_log::default::Default,
        agent_only(),
        "haproxy.log",
    ),
    (
        "filebeat.hashicorp_vault_audit.default",
        &filebeat::hashicorp_vault_audit::default::Default,
        pushed(Framing::Body),
        "hashicorp_vault.audit",
    ),
    (
        "filebeat.hashicorp_vault_log.default",
        &filebeat::hashicorp_vault_log::default::Default,
        agent_only(),
        "hashicorp_vault.log",
    ),
    (
        "filebeat.hashicorp_vault_metrics.default",
        &filebeat::hashicorp_vault_metrics::default::Default,
        agent_only(),
        "hashicorp_vault.metrics",
    ),
    (
        "filebeat.hid_bravura_monitor_log.default",
        &filebeat::hid_bravura_monitor_log::default::Default,
        agent_only(),
        "hid_bravura_monitor.log",
    ),
    (
        "filebeat.hid_bravura_monitor_winlog.default",
        &filebeat::hid_bravura_monitor_winlog::default::Default,
        agent_only(),
        "hid_bravura_monitor.winlog",
    ),
    (
        "filebeat.iis_access.default",
        &filebeat::iis_access::default::Default,
        agent_only(),
        "iis.access",
    ),
    (
        "filebeat.iis_error.default",
        &filebeat::iis_error::default::Default,
        agent_only(),
        "iis.error",
    ),
    (
        "filebeat.imperva_securesphere.default",
        &filebeat::imperva_securesphere::default::Default,
        pushed(Framing::Body),
        "imperva.securesphere",
    ),
    (
        "filebeat.infoblox_nios_log.default",
        &filebeat::infoblox_nios_log::default::Default,
        pushed(Framing::Line),
        "infoblox_nios.log",
    ),
    (
        "filebeat.iptables_log.default",
        &filebeat::iptables_log::default::Default,
        pushed(Framing::Line),
        "iptables.log",
    ),
    (
        "filebeat.jamf_pro_events.default",
        &filebeat::jamf_pro_events::default::Default,
        pushed(Framing::Body),
        "jamf_pro.events",
    ),
    (
        "filebeat.jamf_pro_inventory.default",
        &filebeat::jamf_pro_inventory::default::Default,
        fetched(),
        "jamf_pro.inventory",
    ),
    (
        "filebeat.jumpcloud_events.default",
        &filebeat::jumpcloud_events::default::Default,
        fetched(),
        "jumpcloud.events",
    ),
    (
        "filebeat.juniper_junos_log.default",
        &filebeat::juniper_junos_log::default::Default,
        pushed(Framing::Body),
        "juniper_junos.log",
    ),
    (
        "filebeat.juniper_netscreen_log.default",
        &filebeat::juniper_netscreen_log::default::Default,
        pushed(Framing::Body),
        "juniper_netscreen.log",
    ),
    (
        "filebeat.juniper_srx_log.default",
        &filebeat::juniper_srx_log::default::Default,
        pushed(Framing::Body),
        "juniper_srx.log",
    ),
    (
        "filebeat.jupiter_one_asset.default",
        &filebeat::jupiter_one_asset::default::Default,
        fetched(),
        "jupiter_one.asset",
    ),
    (
        "filebeat.keeper_security_siem_integration_audit.default",
        &filebeat::keeper_security_siem_integration_audit::default::Default,
        agent_only(),
        "keeper_security_siem_integration.audit",
    ),
    (
        "filebeat.keycloak_log.default",
        &filebeat::keycloak_log::default::Default,
        agent_only(),
        "keycloak.log",
    ),
    (
        "filebeat.kibana_audit.default",
        &filebeat::kibana_audit::default::Default,
        agent_only(),
        "kibana.audit",
    ),
    (
        "filebeat.kibana_log.default",
        &filebeat::kibana_log::default::Default,
        agent_only(),
        "kibana.log",
    ),
    (
        "filebeat.kolide_audit.default",
        &filebeat::kolide_audit::default::Default,
        fetched(),
        "kolide.audit",
    ),
    (
        "filebeat.kolide_auth.default",
        &filebeat::kolide_auth::default::Default,
        fetched(),
        "kolide.auth",
    ),
    (
        "filebeat.kolide_deprovisioned_person.default",
        &filebeat::kolide_deprovisioned_person::default::Default,
        fetched(),
        "kolide.deprovisioned_person",
    ),
    (
        "filebeat.kolide_device.default",
        &filebeat::kolide_device::default::Default,
        fetched(),
        "kolide.device",
    ),
    (
        "filebeat.kolide_device_check.default",
        &filebeat::kolide_device_check::default::Default,
        fetched(),
        "kolide.device_check",
    ),
    (
        "filebeat.kolide_issues.default",
        &filebeat::kolide_issues::default::Default,
        fetched(),
        "kolide.issues",
    ),
    (
        "filebeat.kolide_osquery_result.default",
        &filebeat::kolide_osquery_result::default::Default,
        fetched(),
        "kolide.osquery_result",
    ),
    (
        "filebeat.kolide_osquery_status.default",
        &filebeat::kolide_osquery_status::default::Default,
        fetched(),
        "kolide.osquery_status",
    ),
    (
        "filebeat.kolide_people.default",
        &filebeat::kolide_people::default::Default,
        fetched(),
        "kolide.people",
    ),
    (
        "filebeat.kolide_request.default",
        &filebeat::kolide_request::default::Default,
        fetched(),
        "kolide.request",
    ),
    (
        "filebeat.kubernetes_audit_logs.default",
        &filebeat::kubernetes_audit_logs::default::Default,
        fetched(),
        "kubernetes.audit_logs",
    ),
    (
        "filebeat.kubernetes_container_logs.default",
        &filebeat::kubernetes_container_logs::default::Default,
        agent_only(),
        "kubernetes.container_logs",
    ),
    (
        "filebeat.lumos_activity_logs.default",
        &filebeat::lumos_activity_logs::default::Default,
        fetched(),
        "lumos.activity_logs",
    ),
    (
        "filebeat.lyve_cloud_audit.default",
        &filebeat::lyve_cloud_audit::default::Default,
        fetched(),
        "lyve_cloud.audit",
    ),
    (
        "filebeat.m365_defender_alert.default",
        &filebeat::m365_defender_alert::default::Default,
        fetched(),
        "m365_defender.alert",
    ),
    (
        "filebeat.m365_defender_event.default",
        &filebeat::m365_defender_event::default::Default,
        fetched(),
        "m365_defender.event",
    ),
    (
        "filebeat.m365_defender_incident.default",
        &filebeat::m365_defender_incident::default::Default,
        fetched(),
        "m365_defender.incident",
    ),
    (
        "filebeat.m365_defender_vulnerability.default",
        &filebeat::m365_defender_vulnerability::default::Default,
        fetched(),
        "m365_defender.vulnerability",
    ),
    (
        "filebeat.macos_advanced_monitoring.default",
        &filebeat::macos_advanced_monitoring::default::Default,
        agent_only(),
        "macos.advanced_monitoring",
    ),
    (
        "filebeat.macos_authentication.default",
        &filebeat::macos_authentication::default::Default,
        agent_only(),
        "macos.authentication",
    ),
    (
        "filebeat.macos_file_read_write.default",
        &filebeat::macos_file_read_write::default::Default,
        agent_only(),
        "macos.file_read_write",
    ),
    (
        "filebeat.macos_network_activity.default",
        &filebeat::macos_network_activity::default::Default,
        agent_only(),
        "macos.network_activity",
    ),
    (
        "filebeat.macos_process_execution_monitoring.default",
        &filebeat::macos_process_execution_monitoring::default::Default,
        agent_only(),
        "macos.process_execution_monitoring",
    ),
    (
        "filebeat.macos_system_change.default",
        &filebeat::macos_system_change::default::Default,
        agent_only(),
        "macos.system_change",
    ),
    (
        "filebeat.macos_user_and_account_management.default",
        &filebeat::macos_user_and_account_management::default::Default,
        agent_only(),
        "macos.user_and_account_management",
    ),
    (
        "filebeat.mattermost_audit.default",
        &filebeat::mattermost_audit::default::Default,
        agent_only(),
        "mattermost.audit",
    ),
    (
        "filebeat.microsoft_defender_endpoint_log.default",
        &filebeat::microsoft_defender_endpoint_log::default::Default,
        fetched(),
        "microsoft_defender_endpoint.log",
    ),
    (
        "filebeat.microsoft_defender_endpoint_machine.default",
        &filebeat::microsoft_defender_endpoint_machine::default::Default,
        fetched(),
        "microsoft_defender_endpoint.machine",
    ),
    (
        "filebeat.microsoft_defender_endpoint_machine_action.default",
        &filebeat::microsoft_defender_endpoint_machine_action::default::Default,
        fetched(),
        "microsoft_defender_endpoint.machine_action",
    ),
    (
        "filebeat.microsoft_defender_endpoint_vulnerability.default",
        &filebeat::microsoft_defender_endpoint_vulnerability::default::Default,
        fetched(),
        "microsoft_defender_endpoint.vulnerability",
    ),
    (
        "filebeat.microsoft_dhcp_log.default",
        &filebeat::microsoft_dhcp_log::default::Default,
        agent_only(),
        "microsoft_dhcp.log",
    ),
    (
        "filebeat.microsoft_dnsserver_analytical.default",
        &filebeat::microsoft_dnsserver_analytical::default::Default,
        agent_only(),
        "microsoft_dnsserver.analytical",
    ),
    (
        "filebeat.microsoft_dnsserver_audit.default",
        &filebeat::microsoft_dnsserver_audit::default::Default,
        agent_only(),
        "microsoft_dnsserver.audit",
    ),
    (
        "filebeat.microsoft_exchange_online_message_trace_log.default",
        &filebeat::microsoft_exchange_online_message_trace_log::default::Default,
        fetched(),
        "microsoft_exchange_online_message_trace.log",
    ),
    (
        "filebeat.microsoft_exchange_server_httpproxy.default",
        &filebeat::microsoft_exchange_server_httpproxy::default::Default,
        agent_only(),
        "microsoft_exchange_server.httpproxy",
    ),
    (
        "filebeat.microsoft_exchange_server_imap4_pop3.default",
        &filebeat::microsoft_exchange_server_imap4_pop3::default::Default,
        agent_only(),
        "microsoft_exchange_server.imap4_pop3",
    ),
    (
        "filebeat.microsoft_exchange_server_messagetracking.default",
        &filebeat::microsoft_exchange_server_messagetracking::default::Default,
        agent_only(),
        "microsoft_exchange_server.messagetracking",
    ),
    (
        "filebeat.microsoft_exchange_server_smtp.default",
        &filebeat::microsoft_exchange_server_smtp::default::Default,
        agent_only(),
        "microsoft_exchange_server.smtp",
    ),
    (
        "filebeat.mimecast_archive_search_logs.default",
        &filebeat::mimecast_archive_search_logs::default::Default,
        fetched(),
        "mimecast.archive_search_logs",
    ),
    (
        "filebeat.mimecast_audit_events.default",
        &filebeat::mimecast_audit_events::default::Default,
        fetched(),
        "mimecast.audit_events",
    ),
    (
        "filebeat.mimecast_cloud_integrated_logs.default",
        &filebeat::mimecast_cloud_integrated_logs::default::Default,
        fetched(),
        "mimecast.cloud_integrated_logs",
    ),
    (
        "filebeat.mimecast_dlp_logs.default",
        &filebeat::mimecast_dlp_logs::default::Default,
        fetched(),
        "mimecast.dlp_logs",
    ),
    (
        "filebeat.mimecast_message_release_logs.default",
        &filebeat::mimecast_message_release_logs::default::Default,
        fetched(),
        "mimecast.message_release_logs",
    ),
    (
        "filebeat.mimecast_siem_logs.default",
        &filebeat::mimecast_siem_logs::default::Default,
        fetched(),
        "mimecast.siem_logs",
    ),
    (
        "filebeat.mimecast_siem_logs.v1_pipeline",
        &filebeat::mimecast_siem_logs::v1_pipeline::V1Pipeline,
        fetched(),
        "mimecast.siem_logs",
    ),
    (
        "filebeat.mimecast_siem_logs.v2_pipeline",
        &filebeat::mimecast_siem_logs::v2_pipeline::V2Pipeline,
        fetched(),
        "mimecast.siem_logs",
    ),
    (
        "filebeat.mimecast_threat_intel_malware_customer.default",
        &filebeat::mimecast_threat_intel_malware_customer::default::Default,
        fetched(),
        "mimecast.threat_intel_malware_customer",
    ),
    (
        "filebeat.mimecast_threat_intel_malware_grid.default",
        &filebeat::mimecast_threat_intel_malware_grid::default::Default,
        fetched(),
        "mimecast.threat_intel_malware_grid",
    ),
    (
        "filebeat.mimecast_ttp_ap_logs.default",
        &filebeat::mimecast_ttp_ap_logs::default::Default,
        fetched(),
        "mimecast.ttp_ap_logs",
    ),
    (
        "filebeat.mimecast_ttp_ip_logs.default",
        &filebeat::mimecast_ttp_ip_logs::default::Default,
        fetched(),
        "mimecast.ttp_ip_logs",
    ),
    (
        "filebeat.mimecast_ttp_url_logs.default",
        &filebeat::mimecast_ttp_url_logs::default::Default,
        fetched(),
        "mimecast.ttp_url_logs",
    ),
    (
        "filebeat.miniflux_feed_entry.default",
        &filebeat::miniflux_feed_entry::default::Default,
        fetched(),
        "miniflux.feed_entry",
    ),
    (
        "filebeat.modsecurity_auditlog.default",
        &filebeat::modsecurity_auditlog::default::Default,
        agent_only(),
        "modsecurity.auditlog",
    ),
    (
        "filebeat.mongodb_log.default",
        &filebeat::mongodb_log::default::Default,
        agent_only(),
        "mongodb.log",
    ),
    (
        "filebeat.mysql_enterprise_audit.default",
        &filebeat::mysql_enterprise_audit::default::Default,
        agent_only(),
        "mysql_enterprise.audit",
    ),
    (
        "filebeat.nats_log.default",
        &filebeat::nats_log::default::Default,
        agent_only(),
        "nats.log",
    ),
    (
        "filebeat.netbox_devices.default",
        &filebeat::netbox_devices::default::Default,
        fetched(),
        "netbox.devices",
    ),
    (
        "filebeat.netbox_ips.default",
        &filebeat::netbox_ips::default::Default,
        fetched(),
        "netbox.ips",
    ),
    (
        "filebeat.netflow_log.default",
        &filebeat::netflow_log::default::Default,
        agent_only(),
        "netflow.log",
    ),
    (
        "filebeat.netscout_sightline.default",
        &filebeat::netscout_sightline::default::Default,
        pushed(Framing::Body),
        "netscout.sightline",
    ),
    (
        "filebeat.nextron_thor_thor_forwarding.default",
        &filebeat::nextron_thor_thor_forwarding::default::Default,
        fetched(),
        "nextron_thor.thor_forwarding",
    ),
    (
        "filebeat.nginx_access.default",
        &filebeat::nginx_access::default::Default,
        agent_only(),
        "nginx.access",
    ),
    (
        "filebeat.nginx_error.default",
        &filebeat::nginx_error::default::Default,
        agent_only(),
        "nginx.error",
    ),
    (
        "filebeat.o365.default",
        &filebeat::o365::default::Default,
        fetched(),
        "o365.audit",
    ),
    (
        "filebeat.okta.default",
        &filebeat::okta::default::Default,
        fetched(),
        "okta.system",
    ),
    // `panw.default` routes on log type and holds the CSV parse and converts
    // the per-type entries depend on. The per-type entries suit a feed already
    // narrowed to one log type.
    (
        "filebeat.osquery_result.default",
        &filebeat::osquery_result::default::Default,
        agent_only(),
        "osquery.result",
    ),
    (
        "filebeat.panw.audit",
        &filebeat::panw::audit::Audit,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.authentication",
        &filebeat::panw::authentication::Authentication,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.correlated_event",
        &filebeat::panw::correlated_event::CorrelatedEvent,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.decryption",
        &filebeat::panw::decryption::Decryption,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.default",
        &filebeat::panw::default::Default,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.globalprotect",
        &filebeat::panw::globalprotect::Globalprotect,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.gtp",
        &filebeat::panw::gtp::Gtp,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.hipmatch",
        &filebeat::panw::hipmatch::Hipmatch,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.ip_tag",
        &filebeat::panw::ip_tag::IpTag,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.sctp",
        &filebeat::panw::sctp::Sctp,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.system",
        &filebeat::panw::system::System,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.traffic",
        &filebeat::panw::traffic::Traffic,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.tunnel_inspection",
        &filebeat::panw::tunnel_inspection::TunnelInspection,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw.userid",
        &filebeat::panw::userid::Userid,
        pushed(Framing::Body),
        "panw.panos",
    ),
    (
        "filebeat.panw_metrics_system.default",
        &filebeat::panw_metrics_system::default::Default,
        agent_only(),
        "panw_metrics.system",
    ),
    (
        "filebeat.pfsense_log.default",
        &filebeat::pfsense_log::default::Default,
        pushed(Framing::Line),
        "pfsense.log",
    ),
    (
        "filebeat.php_fpm_pool.default",
        &filebeat::php_fpm_pool::default::Default,
        fetched(),
        "php_fpm.pool",
    ),
    (
        "filebeat.php_fpm_process.default",
        &filebeat::php_fpm_process::default::Default,
        fetched(),
        "php_fpm.process",
    ),
    (
        "filebeat.ping_federate_admin.default",
        &filebeat::ping_federate_admin::default::Default,
        agent_only(),
        "ping_federate.admin",
    ),
    (
        "filebeat.ping_federate_audit.default",
        &filebeat::ping_federate_audit::default::Default,
        pushed(Framing::Body),
        "ping_federate.audit",
    ),
    (
        "filebeat.ping_one_audit.default",
        &filebeat::ping_one_audit::default::Default,
        pushed(Framing::Body),
        "ping_one.audit",
    ),
    (
        "filebeat.platform_observability_kibana_audit.default",
        &filebeat::platform_observability_kibana_audit::default::Default,
        agent_only(),
        "platform_observability.kibana_audit",
    ),
    (
        "filebeat.platform_observability_kibana_log.default",
        &filebeat::platform_observability_kibana_log::default::Default,
        agent_only(),
        "platform_observability.kibana_log",
    ),
    (
        "filebeat.postgresql_activity.default",
        &filebeat::postgresql_activity::default::Default,
        agent_only(),
        "postgresql.activity",
    ),
    (
        "filebeat.postgresql_log.default",
        &filebeat::postgresql_log::default::Default,
        agent_only(),
        "postgresql.log",
    ),
    (
        "filebeat.pps_log.default",
        &filebeat::pps_log::default::Default,
        pushed(Framing::Line),
        "pps.log",
    ),
    (
        "filebeat.prisma_access_event.default",
        &filebeat::prisma_access_event::default::Default,
        pushed(Framing::Body),
        "prisma_access.event",
    ),
    (
        "filebeat.proofpoint_itm_report.default",
        &filebeat::proofpoint_itm_report::default::Default,
        fetched(),
        "proofpoint_itm.report",
    ),
    (
        "filebeat.proofpoint_on_demand_audit.default",
        &filebeat::proofpoint_on_demand_audit::default::Default,
        fetched(),
        "proofpoint_on_demand.audit",
    ),
    (
        "filebeat.proofpoint_on_demand_mail.default",
        &filebeat::proofpoint_on_demand_mail::default::Default,
        fetched(),
        "proofpoint_on_demand.mail",
    ),
    (
        "filebeat.proofpoint_on_demand_message.default",
        &filebeat::proofpoint_on_demand_message::default::Default,
        fetched(),
        "proofpoint_on_demand.message",
    ),
    (
        "filebeat.pulse_connect_secure_log.default",
        &filebeat::pulse_connect_secure_log::default::Default,
        pushed(Framing::Line),
        "pulse_connect_secure.log",
    ),
    (
        "filebeat.qnap_nas_log.default",
        &filebeat::qnap_nas_log::default::Default,
        pushed(Framing::Line),
        "qnap_nas.log",
    ),
    (
        "filebeat.qualys_vmdr_asset_host_detection.default",
        &filebeat::qualys_vmdr_asset_host_detection::default::Default,
        fetched(),
        "qualys_vmdr.asset_host_detection",
    ),
    (
        "filebeat.qualys_vmdr_knowledge_base.default",
        &filebeat::qualys_vmdr_knowledge_base::default::Default,
        fetched(),
        "qualys_vmdr.knowledge_base",
    ),
    (
        "filebeat.qualys_vmdr_user_activity.default",
        &filebeat::qualys_vmdr_user_activity::default::Default,
        fetched(),
        "qualys_vmdr.user_activity",
    ),
    (
        "filebeat.qualys_was_vulnerability.default",
        &filebeat::qualys_was_vulnerability::default::Default,
        fetched(),
        "qualys_was.vulnerability",
    ),
    (
        "filebeat.rabbitmq_log.default",
        &filebeat::rabbitmq_log::default::Default,
        agent_only(),
        "rabbitmq.log",
    ),
    (
        "filebeat.redis_log.default",
        &filebeat::redis_log::default::Default,
        agent_only(),
        "redis.log",
    ),
    (
        "filebeat.sailpoint_identity_sc_events.default",
        &filebeat::sailpoint_identity_sc_events::default::Default,
        fetched(),
        "sailpoint_identity_sc.events",
    ),
    (
        "filebeat.santa_log.default",
        &filebeat::santa_log::default::Default,
        agent_only(),
        "santa.log",
    ),
    (
        "filebeat.sentinel_one_activity.default",
        &filebeat::sentinel_one_activity::default::Default,
        fetched(),
        "sentinel_one.activity",
    ),
    (
        "filebeat.sentinel_one_agent.default",
        &filebeat::sentinel_one_agent::default::Default,
        fetched(),
        "sentinel_one.agent",
    ),
    (
        "filebeat.sentinel_one_alert.default",
        &filebeat::sentinel_one_alert::default::Default,
        fetched(),
        "sentinel_one.alert",
    ),
    (
        "filebeat.sentinel_one_application.default",
        &filebeat::sentinel_one_application::default::Default,
        fetched(),
        "sentinel_one.application",
    ),
    (
        "filebeat.sentinel_one_application_risk.default",
        &filebeat::sentinel_one_application_risk::default::Default,
        fetched(),
        "sentinel_one.application_risk",
    ),
    (
        "filebeat.sentinel_one_group.default",
        &filebeat::sentinel_one_group::default::Default,
        fetched(),
        "sentinel_one.group",
    ),
    (
        "filebeat.sentinel_one_threat.default",
        &filebeat::sentinel_one_threat::default::Default,
        fetched(),
        "sentinel_one.threat",
    ),
    (
        "filebeat.sentinel_one_threat_event.default",
        &filebeat::sentinel_one_threat_event::default::Default,
        fetched(),
        "sentinel_one.threat_event",
    ),
    (
        "filebeat.sentinel_one_unified_alert.default",
        &filebeat::sentinel_one_unified_alert::default::Default,
        fetched(),
        "sentinel_one.unified_alert",
    ),
    (
        "filebeat.slack_audit.default",
        &filebeat::slack_audit::default::Default,
        fetched(),
        "slack.audit",
    ),
    (
        "filebeat.snort_log.default",
        &filebeat::snort_log::default::Default,
        pushed(Framing::Line),
        "snort.log",
    ),
    (
        "filebeat.snyk_audit_logs.default",
        &filebeat::snyk_audit_logs::default::Default,
        fetched(),
        "snyk.audit_logs",
    ),
    (
        "filebeat.snyk_issues.default",
        &filebeat::snyk_issues::default::Default,
        fetched(),
        "snyk.issues",
    ),
    (
        "filebeat.sonicwall_firewall_log.default",
        &filebeat::sonicwall_firewall_log::default::Default,
        pushed(Framing::Body),
        "sonicwall_firewall.log",
    ),
    (
        "filebeat.sophos_central_alert.default",
        &filebeat::sophos_central_alert::default::Default,
        fetched(),
        "sophos_central.alert",
    ),
    (
        "filebeat.sophos_central_event.default",
        &filebeat::sophos_central_event::default::Default,
        fetched(),
        "sophos_central.event",
    ),
    (
        "filebeat.sophos_utm.default",
        &filebeat::sophos_utm::default::Default,
        pushed(Framing::Line),
        "sophos.utm",
    ),
    (
        "filebeat.sophos_xg.default",
        &filebeat::sophos_xg::default::Default,
        pushed(Framing::Line),
        "sophos.xg",
    ),
    (
        "filebeat.spring_boot_audit_events.default",
        &filebeat::spring_boot_audit_events::default::Default,
        fetched(),
        "spring_boot.audit_events",
    ),
    (
        "filebeat.spring_boot_gc.default",
        &filebeat::spring_boot_gc::default::Default,
        agent_only(),
        "spring_boot.gc",
    ),
    (
        "filebeat.spring_boot_http_trace.default",
        &filebeat::spring_boot_http_trace::default::Default,
        fetched(),
        "spring_boot.http_trace",
    ),
    (
        "filebeat.spring_boot_memory.default",
        &filebeat::spring_boot_memory::default::Default,
        agent_only(),
        "spring_boot.memory",
    ),
    (
        "filebeat.spring_boot_threading.default",
        &filebeat::spring_boot_threading::default::Default,
        agent_only(),
        "spring_boot.threading",
    ),
    (
        "filebeat.squid_log.default",
        &filebeat::squid_log::default::Default,
        pushed(Framing::Body),
        "squid.log",
    ),
    (
        "filebeat.stan_log.default",
        &filebeat::stan_log::default::Default,
        agent_only(),
        "stan.log",
    ),
    (
        "filebeat.suricata_eve.default",
        &filebeat::suricata_eve::default::Default,
        agent_only(),
        "suricata.eve",
    ),
    (
        "filebeat.symantec_endpoint_security_event.default",
        &filebeat::symantec_endpoint_security_event::default::Default,
        fetched(),
        "symantec_endpoint_security.event",
    ),
    (
        "filebeat.symantec_endpoint_security_incident.default",
        &filebeat::symantec_endpoint_security_incident::default::Default,
        fetched(),
        "symantec_endpoint_security.incident",
    ),
    (
        "filebeat.syslog_router_log.default",
        &filebeat::syslog_router_log::default::Default,
        pushed(Framing::Body),
        "syslog_router.log",
    ),
    (
        "filebeat.system_audit_package.default",
        &filebeat::system_audit_package::default::Default,
        agent_only(),
        "system_audit.package",
    ),
    (
        "filebeat.tenable_sc_asset.default",
        &filebeat::tenable_sc_asset::default::Default,
        fetched(),
        "tenable_sc.asset",
    ),
    (
        "filebeat.tenable_sc_plugin.default",
        &filebeat::tenable_sc_plugin::default::Default,
        fetched(),
        "tenable_sc.plugin",
    ),
    (
        "filebeat.tenable_sc_vulnerability.default",
        &filebeat::tenable_sc_vulnerability::default::Default,
        fetched(),
        "tenable_sc.vulnerability",
    ),
    (
        "filebeat.tetragon_log.default",
        &filebeat::tetragon_log::default::Default,
        agent_only(),
        "tetragon.log",
    ),
    (
        "filebeat.thycotic_ss_logs.default",
        &filebeat::thycotic_ss_logs::default::Default,
        pushed(Framing::Body),
        "thycotic_ss.logs",
    ),
    (
        "filebeat.ti_cif3_feed.default",
        &filebeat::ti_cif3_feed::default::Default,
        fetched(),
        "ti_cif3.feed",
    ),
    (
        "filebeat.ti_cybersixgill_threat.default",
        &filebeat::ti_cybersixgill_threat::default::Default,
        fetched(),
        "ti_cybersixgill.threat",
    ),
    (
        "filebeat.ti_domaintools_domaindiscovery_feed.default",
        &filebeat::ti_domaintools_domaindiscovery_feed::default::Default,
        fetched(),
        "ti_domaintools.domaindiscovery_feed",
    ),
    (
        "filebeat.ti_domaintools_domainhotlist_feed.default",
        &filebeat::ti_domaintools_domainhotlist_feed::default::Default,
        fetched(),
        "ti_domaintools.domainhotlist_feed",
    ),
    (
        "filebeat.ti_domaintools_domainrdap_feed.default",
        &filebeat::ti_domaintools_domainrdap_feed::default::Default,
        fetched(),
        "ti_domaintools.domainrdap_feed",
    ),
    (
        "filebeat.ti_domaintools_domainrisk_feed.default",
        &filebeat::ti_domaintools_domainrisk_feed::default::Default,
        fetched(),
        "ti_domaintools.domainrisk_feed",
    ),
    (
        "filebeat.ti_domaintools_nad_feed.default",
        &filebeat::ti_domaintools_nad_feed::default::Default,
        fetched(),
        "ti_domaintools.nad_feed",
    ),
    (
        "filebeat.ti_domaintools_nod_feed.default",
        &filebeat::ti_domaintools_nod_feed::default::Default,
        fetched(),
        "ti_domaintools.nod_feed",
    ),
    (
        "filebeat.ti_eclecticiq_threat.default",
        &filebeat::ti_eclecticiq_threat::default::Default,
        fetched(),
        "ti_eclecticiq.threat",
    ),
    (
        "filebeat.ti_greynoise_ip.default",
        &filebeat::ti_greynoise_ip::default::Default,
        fetched(),
        "ti_greynoise.ip",
    ),
    (
        "filebeat.ti_maltiverse_indicator.default",
        &filebeat::ti_maltiverse_indicator::default::Default,
        fetched(),
        "ti_maltiverse.indicator",
    ),
    (
        "filebeat.ti_socradar_feeds_feed.default",
        &filebeat::ti_socradar_feeds_feed::default::Default,
        fetched(),
        "ti_socradar_feeds.feed",
    ),
    (
        "filebeat.ti_strider_indicator.default",
        &filebeat::ti_strider_indicator::default::Default,
        fetched(),
        "ti_strider.indicator",
    ),
    (
        "filebeat.ti_ticura_indicator.default",
        &filebeat::ti_ticura_indicator::default::Default,
        fetched(),
        "ti_ticura.indicator",
    ),
    (
        "filebeat.tines_audit_logs.default",
        &filebeat::tines_audit_logs::default::Default,
        fetched(),
        "tines.audit_logs",
    ),
    (
        "filebeat.tines_time_saved.default",
        &filebeat::tines_time_saved::default::Default,
        fetched(),
        "tines.time_saved",
    ),
    (
        "filebeat.tomcat_log.default",
        &filebeat::tomcat_log::default::Default,
        pushed(Framing::Body),
        "tomcat.log",
    ),
    (
        "filebeat.trendmicro_deep_security.default",
        &filebeat::trendmicro_deep_security::default::Default,
        pushed(Framing::Line),
        "trendmicro.deep_security",
    ),
    (
        "filebeat.varonis_logs.default",
        &filebeat::varonis_logs::default::Default,
        pushed(Framing::Body),
        "varonis.logs",
    ),
    (
        "filebeat.watchguard_firebox_log.default",
        &filebeat::watchguard_firebox_log::default::Default,
        pushed(Framing::Line),
        "watchguard_firebox.log",
    ),
    (
        "filebeat.windows_applocker_exe_and_dll.default",
        &filebeat::windows_applocker_exe_and_dll::default::Default,
        agent_only(),
        "windows.applocker_exe_and_dll",
    ),
    (
        "filebeat.windows_applocker_msi_and_script.default",
        &filebeat::windows_applocker_msi_and_script::default::Default,
        agent_only(),
        "windows.applocker_msi_and_script",
    ),
    (
        "filebeat.windows_applocker_packaged_app_deployment.default",
        &filebeat::windows_applocker_packaged_app_deployment::default::Default,
        agent_only(),
        "windows.applocker_packaged_app_deployment",
    ),
    (
        "filebeat.windows_applocker_packaged_app_execution.default",
        &filebeat::windows_applocker_packaged_app_execution::default::Default,
        agent_only(),
        "windows.applocker_packaged_app_execution",
    ),
    (
        "filebeat.windows_forwarded.default",
        &filebeat::windows_forwarded::default::Default,
        agent_only(),
        "windows.forwarded",
    ),
    (
        "filebeat.windows_powershell.default",
        &filebeat::windows_powershell::default::Default,
        agent_only(),
        "windows.powershell",
    ),
    (
        "filebeat.windows_powershell_operational.default",
        &filebeat::windows_powershell_operational::default::Default,
        agent_only(),
        "windows.powershell_operational",
    ),
    (
        "filebeat.windows_sysmon_operational.default",
        &filebeat::windows_sysmon_operational::default::Default,
        agent_only(),
        "windows.sysmon_operational",
    ),
    (
        "filebeat.windows_windows_defender.default",
        &filebeat::windows_windows_defender::default::Default,
        agent_only(),
        "windows.windows_defender",
    ),
    (
        "filebeat.withsecure_elements_incidents.default",
        &filebeat::withsecure_elements_incidents::default::Default,
        fetched(),
        "withsecure_elements.incidents",
    ),
    (
        "filebeat.withsecure_elements_security_events.default",
        &filebeat::withsecure_elements_security_events::default::Default,
        fetched(),
        "withsecure_elements.security_events",
    ),
    (
        "filebeat.zeek_capture_loss.default",
        &filebeat::zeek_capture_loss::default::Default,
        agent_only(),
        "zeek.capture_loss",
    ),
    (
        "filebeat.zeek_connection.default",
        &filebeat::zeek_connection::default::Default,
        agent_only(),
        "zeek.connection",
    ),
    (
        "filebeat.zeek_dce_rpc.default",
        &filebeat::zeek_dce_rpc::default::Default,
        agent_only(),
        "zeek.dce_rpc",
    ),
    (
        "filebeat.zeek_dhcp.default",
        &filebeat::zeek_dhcp::default::Default,
        agent_only(),
        "zeek.dhcp",
    ),
    (
        "filebeat.zeek_dnp3.default",
        &filebeat::zeek_dnp3::default::Default,
        agent_only(),
        "zeek.dnp3",
    ),
    (
        "filebeat.zeek_dns.default",
        &filebeat::zeek_dns::default::Default,
        agent_only(),
        "zeek.dns",
    ),
    (
        "filebeat.zeek_dpd.default",
        &filebeat::zeek_dpd::default::Default,
        agent_only(),
        "zeek.dpd",
    ),
    (
        "filebeat.zeek_files.default",
        &filebeat::zeek_files::default::Default,
        agent_only(),
        "zeek.files",
    ),
    (
        "filebeat.zeek_ftp.default",
        &filebeat::zeek_ftp::default::Default,
        agent_only(),
        "zeek.ftp",
    ),
    (
        "filebeat.zeek_http.default",
        &filebeat::zeek_http::default::Default,
        agent_only(),
        "zeek.http",
    ),
    (
        "filebeat.zeek_intel.default",
        &filebeat::zeek_intel::default::Default,
        agent_only(),
        "zeek.intel",
    ),
    (
        "filebeat.zeek_irc.default",
        &filebeat::zeek_irc::default::Default,
        agent_only(),
        "zeek.irc",
    ),
    (
        "filebeat.zeek_kerberos.default",
        &filebeat::zeek_kerberos::default::Default,
        agent_only(),
        "zeek.kerberos",
    ),
    (
        "filebeat.zeek_known_certs.default",
        &filebeat::zeek_known_certs::default::Default,
        agent_only(),
        "zeek.known_certs",
    ),
    (
        "filebeat.zeek_known_hosts.default",
        &filebeat::zeek_known_hosts::default::Default,
        agent_only(),
        "zeek.known_hosts",
    ),
    (
        "filebeat.zeek_known_services.default",
        &filebeat::zeek_known_services::default::Default,
        agent_only(),
        "zeek.known_services",
    ),
    (
        "filebeat.zeek_modbus.default",
        &filebeat::zeek_modbus::default::Default,
        agent_only(),
        "zeek.modbus",
    ),
    (
        "filebeat.zeek_mysql.default",
        &filebeat::zeek_mysql::default::Default,
        agent_only(),
        "zeek.mysql",
    ),
    (
        "filebeat.zeek_notice.default",
        &filebeat::zeek_notice::default::Default,
        agent_only(),
        "zeek.notice",
    ),
    (
        "filebeat.zeek_ntlm.default",
        &filebeat::zeek_ntlm::default::Default,
        agent_only(),
        "zeek.ntlm",
    ),
    (
        "filebeat.zeek_ntp.default",
        &filebeat::zeek_ntp::default::Default,
        agent_only(),
        "zeek.ntp",
    ),
    (
        "filebeat.zeek_ocsp.default",
        &filebeat::zeek_ocsp::default::Default,
        agent_only(),
        "zeek.ocsp",
    ),
    (
        "filebeat.zeek_pe.default",
        &filebeat::zeek_pe::default::Default,
        agent_only(),
        "zeek.pe",
    ),
    (
        "filebeat.zeek_radius.default",
        &filebeat::zeek_radius::default::Default,
        agent_only(),
        "zeek.radius",
    ),
    (
        "filebeat.zeek_rdp.default",
        &filebeat::zeek_rdp::default::Default,
        agent_only(),
        "zeek.rdp",
    ),
    (
        "filebeat.zeek_rfb.default",
        &filebeat::zeek_rfb::default::Default,
        agent_only(),
        "zeek.rfb",
    ),
    (
        "filebeat.zeek_signature.default",
        &filebeat::zeek_signature::default::Default,
        agent_only(),
        "zeek.signature",
    ),
    (
        "filebeat.zeek_sip.default",
        &filebeat::zeek_sip::default::Default,
        agent_only(),
        "zeek.sip",
    ),
    (
        "filebeat.zeek_smb_cmd.default",
        &filebeat::zeek_smb_cmd::default::Default,
        agent_only(),
        "zeek.smb_cmd",
    ),
    (
        "filebeat.zeek_smb_files.default",
        &filebeat::zeek_smb_files::default::Default,
        agent_only(),
        "zeek.smb_files",
    ),
    (
        "filebeat.zeek_smb_mapping.default",
        &filebeat::zeek_smb_mapping::default::Default,
        agent_only(),
        "zeek.smb_mapping",
    ),
    (
        "filebeat.zeek_smtp.default",
        &filebeat::zeek_smtp::default::Default,
        agent_only(),
        "zeek.smtp",
    ),
    (
        "filebeat.zeek_snmp.default",
        &filebeat::zeek_snmp::default::Default,
        agent_only(),
        "zeek.snmp",
    ),
    (
        "filebeat.zeek_socks.default",
        &filebeat::zeek_socks::default::Default,
        agent_only(),
        "zeek.socks",
    ),
    (
        "filebeat.zeek_software.default",
        &filebeat::zeek_software::default::Default,
        agent_only(),
        "zeek.software",
    ),
    (
        "filebeat.zeek_ssh.default",
        &filebeat::zeek_ssh::default::Default,
        agent_only(),
        "zeek.ssh",
    ),
    (
        "filebeat.zeek_ssl.default",
        &filebeat::zeek_ssl::default::Default,
        agent_only(),
        "zeek.ssl",
    ),
    (
        "filebeat.zeek_stats.default",
        &filebeat::zeek_stats::default::Default,
        agent_only(),
        "zeek.stats",
    ),
    (
        "filebeat.zeek_syslog.default",
        &filebeat::zeek_syslog::default::Default,
        agent_only(),
        "zeek.syslog",
    ),
    (
        "filebeat.zeek_traceroute.default",
        &filebeat::zeek_traceroute::default::Default,
        agent_only(),
        "zeek.traceroute",
    ),
    (
        "filebeat.zeek_tunnel.default",
        &filebeat::zeek_tunnel::default::Default,
        agent_only(),
        "zeek.tunnel",
    ),
    (
        "filebeat.zeek_weird.default",
        &filebeat::zeek_weird::default::Default,
        agent_only(),
        "zeek.weird",
    ),
    (
        "filebeat.zeek_x509.default",
        &filebeat::zeek_x509::default::Default,
        agent_only(),
        "zeek.x509",
    ),
    (
        "filebeat.zerofox_alerts.default",
        &filebeat::zerofox_alerts::default::Default,
        fetched(),
        "zerofox.alerts",
    ),
    (
        "filebeat.zeronetworks_audit.default",
        &filebeat::zeronetworks_audit::default::Default,
        fetched(),
        "zeronetworks.audit",
    ),
    (
        "filebeat.zscaler_zia_alerts.default",
        &filebeat::zscaler_zia_alerts::default::Default,
        pushed(Framing::Body),
        "zscaler_zia.alerts",
    ),
    (
        "filebeat.zscaler_zia_audit.default",
        &filebeat::zscaler_zia_audit::default::Default,
        pushed(Framing::Body),
        "zscaler_zia.audit",
    ),
    (
        "filebeat.zscaler_zia_dns.default",
        &filebeat::zscaler_zia_dns::default::Default,
        pushed(Framing::Body),
        "zscaler_zia.dns",
    ),
    (
        "filebeat.zscaler_zia_email_dlp.default",
        &filebeat::zscaler_zia_email_dlp::default::Default,
        pushed(Framing::Body),
        "zscaler_zia.email_dlp",
    ),
    (
        "filebeat.zscaler_zia_endpoint_dlp.default",
        &filebeat::zscaler_zia_endpoint_dlp::default::Default,
        pushed(Framing::Body),
        "zscaler_zia.endpoint_dlp",
    ),
    (
        "filebeat.zscaler_zia_firewall.default",
        &filebeat::zscaler_zia_firewall::default::Default,
        pushed(Framing::Body),
        "zscaler_zia.firewall",
    ),
    (
        "filebeat.zscaler_zia_saas_security.default",
        &filebeat::zscaler_zia_saas_security::default::Default,
        pushed(Framing::Body),
        "zscaler_zia.saas_security",
    ),
    (
        "filebeat.zscaler_zia_saas_security_activity.default",
        &filebeat::zscaler_zia_saas_security_activity::default::Default,
        pushed(Framing::Body),
        "zscaler_zia.saas_security_activity",
    ),
    (
        "filebeat.zscaler_zia_sandbox_report.default",
        &filebeat::zscaler_zia_sandbox_report::default::Default,
        fetched(),
        "zscaler_zia.sandbox_report",
    ),
    (
        "filebeat.zscaler_zia_sandbox_verdict.default",
        &filebeat::zscaler_zia_sandbox_verdict::default::Default,
        pushed(Framing::Body),
        "zscaler_zia.sandbox_verdict",
    ),
    (
        "filebeat.zscaler_zia_tunnel.default",
        &filebeat::zscaler_zia_tunnel::default::Default,
        pushed(Framing::Body),
        "zscaler_zia.tunnel",
    ),
    (
        "filebeat.zscaler_zia_web.default",
        &filebeat::zscaler_zia_web::default::Default,
        pushed(Framing::Body),
        "zscaler_zia.web",
    ),
];

/// Resolve a source name to its transform.
pub fn lookup(name: &str) -> Option<&'static (dyn Transform + Sync)> {
    TRANSFORMS
        .iter()
        .find(|(key, ..)| *key == name)
        .map(|(_, t, ..)| *t)
}

/// Every way a source's payload can reach this service.
pub fn intake(name: &str) -> Option<Intake> {
    TRANSFORMS
        .iter()
        .find(|(key, ..)| *key == name)
        .map(|(_, _, intake, _)| *intake)
}

/// The data stream this source's events belong to, `<package>.<data_stream>`.
///
/// Beats and the Agent stamp this on every event; the receiver and the fetcher
/// have no way to know it, so the service supplies it from here.
pub fn dataset(name: &str) -> Option<&'static str> {
    TRANSFORMS
        .iter()
        .find(|(key, ..)| *key == name)
        .map(|(.., dataset)| *dataset)
}

/// Every source name this service accepts.
pub fn sources() -> impl Iterator<Item = &'static str> {
    TRANSFORMS.iter().map(|(key, ..)| *key)
}

/// Every source that can be delivered in `envelope`.
pub fn sources_accepting(envelope: Envelope) -> impl Iterator<Item = &'static str> {
    TRANSFORMS
        .iter()
        .filter(move |(_, _, intake, _)| intake.accepts(envelope))
        .map(|(key, ..)| *key)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    #[test]
    fn resolves_a_known_source() {
        assert!(lookup("filebeat.okta.default").is_some());
    }

    /// Which intakes each source has are declared in `sources.yaml` and checked
    /// below. All this adds is the two invariants the declaration cannot state:
    /// Beats always works, and an unknown name has no intake at all.
    ///
    /// A source may be pushed by a device or fetchable or NEITHER: an ETW trace
    /// and a Windows event log are read off the host by the agent, and there is
    /// no other route to the same bytes. What no source may be is both, which
    /// would mean one payload arriving in two different wrappers.
    #[test]
    fn every_source_accepts_beats_and_at_most_one_other() {
        assert_eq!(
            sources_accepting(Envelope::Beats).count(),
            sources().count(),
            "every source has an Elastic integration, so Beats always applies"
        );
        for (name, _, intake, _) in TRANSFORMS {
            assert!(
                !(intake.accepts(Envelope::Receiver) && intake.accepts(Envelope::Fetcher)),
                "{name} claims both a device push and a fetch"
            );
        }
        assert_eq!(intake("filebeat.nosuchthing"), None);
    }

    /// Framing describes a syslog delivery, so it exists exactly when one is
    /// possible. A fetched source carrying one would be read as a device.
    #[test]
    fn framing_is_present_exactly_when_the_receiver_is() {
        for (name, _, intake, _) in TRANSFORMS {
            assert_eq!(
                intake.accepts(Envelope::Receiver),
                intake.framing.is_some(),
                "{name} disagrees with itself about the receiver"
            );
        }
    }

    #[test]
    fn rejects_an_unknown_source() {
        assert!(lookup("filebeat.nosuchthing").is_none());
    }

    #[test]
    fn every_registered_source_resolves() {
        for name in sources() {
            assert!(lookup(name).is_some(), "{name} did not resolve");
        }
    }

    /// `sources.yaml` is the one declaration per source; the four tools that
    /// used to carry their own copy all read it. This registry cannot, because
    /// every entry names a Rust type, so it is checked against it instead --
    /// a source declared and never wired here fails, and so does the reverse.
    #[test]
    fn the_registry_matches_the_source_declaration() {
        use std::collections::BTreeMap;

        #[derive(serde::Deserialize)]
        struct Declaration {
            sources: BTreeMap<String, Declared>,
        }

        #[derive(serde::Deserialize)]
        struct Declared {
            package: String,
            data_stream: String,
            intakes: Vec<String>,
            framing: Option<String>,
            transforms: Vec<String>,
        }

        const PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/sources.yaml");
        let text = std::fs::read_to_string(PATH).expect("read sources.yaml");
        let declaration: Declaration = serde_yaml_ng::from_str(&text).expect("parse sources.yaml");

        // Compared as text: the declaration is the readable form, and a
        // mismatch has to name what it saw rather than a struct's Debug.
        let mut expected: Vec<(String, String)> = Vec::new();
        for (source, declared) in &declaration.sources {
            for name in &declared.intakes {
                assert!(
                    ["beats", "receiver", "fetcher"].contains(&name.as_str()),
                    "{source} declares intake {name:?}, which is not one"
                );
            }
            let described = describe(
                &declared.intakes,
                declared.framing.as_deref(),
                &format!("{}.{}", declared.package, declared.data_stream),
            );
            for transform in &declared.transforms {
                expected.push((format!("filebeat.{source}.{transform}"), described.clone()));
            }
        }
        expected.sort_by(|a, b| a.0.cmp(&b.0));

        let wired: Vec<(String, String)> = TRANSFORMS
            .iter()
            .map(|(name, _, intake, dataset)| {
                let names: Vec<String> = intake
                    .envelopes
                    .iter()
                    .map(|e| format!("{e:?}").to_lowercase())
                    .collect();
                let framing = intake.framing.map(|f| format!("{f:?}").to_lowercase());
                (
                    (*name).to_owned(),
                    describe(&names, framing.as_deref(), dataset),
                )
            })
            .collect();

        assert_eq!(
            wired, expected,
            "src/registry.rs and sources.yaml disagree on the sources or their intakes"
        );
    }

    /// One string per source, so a mismatch reads as what was declared.
    fn describe(intakes: &[String], framing: Option<&str>, dataset: &str) -> String {
        let mut names: Vec<&str> = intakes.iter().map(String::as_str).collect();
        names.sort_unstable();
        match framing {
            Some(f) => format!("{dataset} {}/{f}", names.join("+")),
            None => format!("{dataset} {}", names.join("+")),
        }
    }

    /// Every source has a dataset, and an unknown name has none.
    #[test]
    fn every_source_has_a_dataset() {
        for name in sources() {
            let dataset = dataset(name).unwrap_or_else(|| panic!("{name} has no dataset"));
            assert!(
                dataset.contains('.') && !dataset.starts_with('.') && !dataset.ends_with('.'),
                "{name}: `{dataset}` is not <package>.<data_stream>"
            );
        }
        assert_eq!(dataset("filebeat.nosuchthing"), None);
    }

    #[test]
    fn names_are_unique_and_sorted() {
        let names: Vec<&str> = sources().collect();
        let mut sorted = names.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(
            names, sorted,
            "registry must be sorted and free of duplicates"
        );
    }
}
